### ISSUE TITLE
To fix: JavaLayerConfigurationsHelperTest

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#1164]
**Description of the issue**: Test failure

**Expected behavior**: Test success

**Steps to reproduce**: 

```shell
cd jib-maven-plugin
./mvnw verify -Pintegration-tests
```

**Environment**: 

Linux rodete

**Log output**: 

```
[INFO] Running com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest
[ERROR] testFromExplodedWar(com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: expected:<[/usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/META-INF, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/META-INF/context.xml, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/Test.jsp, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/empty_dir, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/package, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/package/test.properties, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/lib, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/web.xml]> but was:<[/usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/META-INF, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/META-INF/context.xml, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/Test.jsp, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/empty_dir, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/package, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/classes/package/test.properties, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/lib, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/WEB-INF/web.xml, /usr/local/google/home/qingyangc/clones/jib/jib-maven-plugin/target/test-classes/exploded-war/file]>
	at com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest.assertLayerEntriesUnordered(JavaLayerConfigurationsHelperTest.java:42)
	at com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest.assertSourcePathsUnordered(JavaLayerConfigurationsHelperTest.java:47)
	at com.google.cloud.tools.jib.plugins.common.JavaLayerConfigurationsHelperTest.testFromExplodedWar(JavaLayerConfigurationsHelperTest.java:72)
```

**Comment by chanseokoh** [comment]
I think I hit this. Do `mvn clean` and try again.

**Comment by coollog** [comment]
Ah okay, that did the trick - I guess it was just leftover build files interfering with the test. I noticed in that test, it creates a directory in the exploded-war build output directory. I think we should keep tests hermetic and use temporary directories with the test files copied into them.
