### ISSUE TITLE
Manifest Version issue while pushing Docker hub registry.

### ISSUE THREAD

**Issue by daylight00** [GoogleContainerTools/jib#1193]
**Description of the issue**:
I'm just trying to push spring boot project to my docker hub registry. But, gradle jib task is fails.
Same error message #601. but My isssue is in docker hub registry. not OpenShift or Quay.io
Do you guys have a method of set up manifest version or schema? 
Or plz let me know what problem I have.

Thanks.
**Expected behavior**:

**Steps to reproduce**: 
```
gradle clean build
```
**Environment**: 
mac os high sierra 10.13

**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'org.springframework.boot' version '2.0.6.RELEASE'
    id "io.spring.dependency-management" version "1.0.6.RELEASE"
    id 'com.google.cloud.tools.jib' version '0.9.11'
}

group = 'mygroup'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 11
targetCompatibility = 11
repositories {
    mavenCentral()
}

bootJar {
    manifest
    baseName = 'rapunzel-docker'
    version =  '0.1.0'
}

ext {
    springCloudVersion = 'Finchley.SR1'
}

dependencies {
    implementation('org.springframework.cloud:spring-cloud-starter-netflix-eureka-server')
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    compile('org.springframework.boot:spring-boot-starter-web')
    testImplementation('org.springframework.boot:spring-boot-starter-test')

    compile group: 'com.sun.xml.bind', name: 'jaxb-core', version: '2.2.7'
    compile group: 'com.sun.xml.bind', name: 'jaxb-impl', version: '2.2.7'


}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

jib {
    from {
        image = 'openjdk:11-jdk-slim'
    }
    to {
        image = 'daylight00/rapunzel'
        credHelper = 'osxkeychain'
        auth {
            username = 'daylight00' // Defined in 'gradle.properties'.
            password = 'password'
        }
        tags = ['tag2', 'latest']
    }
    container {
        jvmFlags = ['-Xms512m', '-Xdebug', '-Xmy:flag=jib-rules']
        mainClass = 'mygroup.rapunzel.RapunzelApplication'
        args = ['some', 'args']
        ports = ['8080']
        labels = [key1:'value1', key2:'value2']
        format = 'OCI'
    }
}

tasks.build.dependsOn tasks.jib

```

**Log output**: 
```
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
{"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}

        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
        at com.google.cloud.tools.jib.http.Connection.send(Connection.java:161)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:229)
        ... 11 more
> Task :jib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jib'.
> Tried to push image manifest for registry.hub.docker.com/daylight00/rapunzel:tag2 but failed because: Registry may not support Image Manifest Version 2, Schema 2 | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new
```

**Additional Information**:

**Comment by chanseokoh** [comment]
Looks like `format = 'OCI'` is throwing you off. I believe removing the format setting will at least make it work (which means you will build an image with the Docker spec instead of the OCI spec).

@GoogleContainerTools/java-tools does Docker Hub support OCI? Or, are we not building an OCI image correctly?

**Comment by daylight00** [comment]
@chanseokoh 
Thanks. It works. close issue.

**Comment by briandealwis** [comment]
It looks like [Docker Hub nor the open source `registry` does not yet support OCI images](https://www.opencontainers.org/blog/2018/10/11/oci-image-support-comes-to-open-source-docker-registry) though it's coming.
