### ISSUE TITLE
UNC path is missing hostname: \/

### ISSUE THREAD

**Issue by remmeier** [GoogleContainerTools/jib#1248]
```
The base image requires auth. Trying again for anapsix/alpine-java...
Retrieving registry credentials for registry.hub.docker.com...
Got more than one input Future failure. Logging failures after the first
java.nio.file.InvalidPathException: UNC path is missing hostname: \/
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:113)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.google.cloud.tools.jib.image.ReproducibleLayerBuilder$UniqueTarArchiveEntries.add(ReproducibleLayerBuilder.java:69)
	at com.google.cloud.tools.jib.image.ReproducibleLayerBuilder$UniqueTarArchiveEntries.add(ReproducibleLayerBuilder.java:71)
	at com.google.cloud.tools.jib.image.ReproducibleLayerBuilder$UniqueTarArchiveEntries.add(ReproducibleLayerBuilder.java:71)
	at com.google.cloud.tools.jib.image.ReproducibleLayerBuilder$UniqueTarArchiveEntries.add(ReproducibleLayerBuilder.java:71)
	at com.google.cloud.tools.jib.image.ReproducibleLayerBuilder$UniqueTarArchiveEntries.access$100(ReproducibleLayerBuilder.java:44)
	at com.google.cloud.tools.jib.image.ReproducibleLayerBuilder.build(ReproducibleLayerBuilder.java:111)
	at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:112)
	at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:37)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Environment**

Windows, Gradle 4.10, Java 8

it seems to be a windows-related issue. Not entirely sure what triggers it. The same build worked on very similar machine. And till this day it worked well on both. I recently upgraded to jib 0.10.0, so that could be another possiblity.

One is clearly visible is that UniqueTarArchiveEntries has issues differentiating "/" and "\\" paths. When debugging through the stack before the exception is thrown, I see:

recursive calls to  `ReproducibleLayerBuilder.add` :

```
tarArchiveEntry.name=\/
tarArchiveEntry.name=\app/
tarArchiveEntry.name=\app\classes/
tarArchiveEntry.name=/app/classes/ch/
```

initiall one call to `ReproducibleLayerBuilder.build`:

```
layerEntry.sourceFile=C:\projects\demo\demo-batch\build\classes\java\main\ch
layerEntry.extractionPath=/app/classes/ch 
```

the `tarArchiveEntry.name=\/` then obviously leads to a crash within the Java NIO API.

By hardening UniqueTarArchiveEntries  the issue should get resolved I guess.

**Comment by chanseokoh** [comment]
Seems obvious that this is a Windows issue. I agree `UniqueTarArchiveEntries` needs some hardening.

**Comment by remmeier** [comment]
I was investigating it further to find out why it works in some configurations and not others. I ended up seeing that different versions of 'org.apache.commons:commons-compress' can cause the issue. Seems that they already fixed the issue above. This in turn makes the fix here uncessary. But jib should shade all its dependencies along the lines of https://github.com/project-aries/docker-java-shaded.

**Comment by chanseokoh** [comment]
Apparently, this is a bug in old `org.apache.commons:commons-compress`, so closing.

About embedding dependencies (by shading, for example) like `commons-compress`: assessing the situation as of now, I think this doesn't seem really necessary or worth the effort.

**Comment by Lekinho** [comment]
I've recently experienced this while trying a tar build task with jib.

I don't quite follow very well, what is the resolution here? 
is the commons-compress library fix part of the 1.8 jib dependency jars? or do i need to do something manual?

Thanks

**Comment by chanseokoh** [comment]
Hi @Lekinho,

Jib uses the `commons-compress` library. Most of the time, Gradle will use the right version that Jib wants to use. However, sometimes, your Gradle build may pick up a very old version of `commons-compress`, for example, if your project is a multi-module setup. See this FAQ: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-seeing-method-not-found-or-class-not-found-errors-when-building Also check #2183.

**Comment by chanseokoh** [comment]
If you still experience the same problem after looking at these, feel free to reopen or create a new issue.
