### ISSUE TITLE
AWS ECR CRED HELPER  + AWS CLI with multiple Profiles

### ISSUE THREAD

**Issue by parmarsanjayCLS** [GoogleContainerTools/jib#1252]
**Description of the issue**:
Does gradle plugin work If i've multiple profiles defined for AWS CLI.  I see that you can pass AWS_PROFILE when used with AWS CRED HELPER directly with docker.
```
AWS_PROFILE=profile1 docker pull xxxxxxxxxxxxxxxxxx.dkr.ecr.eu-west1.amazonaws.com/nexus:arch-1547-to-2.14.1-SNAPSHOT
```
**Log output**:
```
com.google.cloud.tools.jib.registry.RegistryUnauthorizedException: Unauthorized for 306520226970.dkr.ecr.us-east-1.amazonaws.com/q2
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:259)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.callWithAllowInsecureRegistryHandling(RegistryEndpointCaller.java:151)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:141)
        at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:355)
        at com.google.cloud.tools.jib.registry.RegistryClient.checkBlob(RegistryClient.java:261)
        at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:79)
        at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:35)
        at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:181)
```

**Comment by loosebazooka** [comment]
@parmarsanjayCLS closing for now, if you have any updates please feel free to comment here.
