### ISSUE TITLE
Flaky test failure on FileOperations.newLockingOutputStream

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1267]
Got an interesting flaky test failure.

```
com.google.cloud.tools.jib.filesystem.FileOperationsTest > testNewLockingOutputStream_newFile FAILED
    java.lang.AssertionError: Lock attempt should have failed
        at org.junit.Assert.fail(Assert.java:88)
        at com.google.cloud.tools.jib.filesystem.FileOperationsTest.verifyWriteWithLock(FileOperationsTest.java:49)
        at com.google.cloud.tools.jib.filesystem.FileOperationsTest.testNewLockingOutputStream_newFile(FileOperationsTest.java:98)
```

Full log: https://source.cloud.google.com/results/invocations/c9d1aec1-105e-4225-89e4-129a3c80390a/log

Test code:
```java
  private static void verifyWriteWithLock(Path file) throws IOException {
    OutputStream fileOutputStream = FileOperations.newLockingOutputStream(file);

    // Checks that the file was locked.
    try {
      FileChannel.open(file, StandardOpenOption.READ).tryLock(0, Long.MAX_VALUE, true);
      Assert.fail("Lock attempt should have failed");

    } catch (OverlappingFileLockException ex) {
      // pass
    }
```

**Comment by briandealwis** [comment]
Is it possible that the test is operating on a networked file system?

**Comment by briandealwis** [comment]
Although the log has disappeared, the invocation details shows that this was on Windows.

**Comment by briandealwis** [comment]
Ah the test is bogus as `tryLock()` may return `null` if the test cannot be acquired.  Plus we should close the `FileChannel`.
