### ISSUE TITLE
ModuleLoadException when trying to run jib built container

### ISSUE THREAD

**Issue by magick93** [GoogleContainerTools/jib#1280]
**Description of the issue**:

I'm trying to build and run a Thorntail Microprofile app using jib. The service works fine without jib, but fails to run when using jibl

**Expected behavior**:

I expect the java application to run the same in the docker container, as without.

**Steps to reproduce**: 

Using the following pom.xm

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>my</groupId>
	<artifactId>ignite-query</artifactId>
	<name>Thorntail Example</name>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>war</packaging>

	<properties>
		<version.thorntail>2.2.1.Final</version.thorntail>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<failOnMissingWebXml>false</failOnMissingWebXml>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.thorntail</groupId>
				<artifactId>bom-all</artifactId>
				<version>${version.thorntail}</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<finalName>demo</finalName>
		<plugins>
			<plugin>
				<groupId>io.thorntail</groupId>
				<artifactId>thorntail-maven-plugin</artifactId>
				<version>${version.thorntail}</version>

				<executions>
					<execution>
						<goals>
							<goal>package</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>0.9.0</version>
				<configuration>
					<to>
						<image>cryptopia/ignite-query</image>
					</to>
					<mainClass>org.wildfly.swarm.Swarm</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>

		<dependency>
			<groupId>io.thorntail</groupId>
			<artifactId>cdi-config</artifactId>
		</dependency>
		<dependency>
			<groupId>io.thorntail</groupId>
			<artifactId>camel-cdi</artifactId>
		</dependency>
		<dependency>
			<groupId>io.thorntail</groupId>
			<artifactId>camel-swagger</artifactId>
		</dependency>
		<dependency>
			<groupId>io.thorntail</groupId>
			<artifactId>camel-core</artifactId>
		</dependency>
		<dependency>
			<groupId>io.thorntail</groupId>
			<artifactId>microprofile-openapi</artifactId>
		</dependency>
	</dependencies>
</project>
```

**Environment**: 

```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Log output**: 

```
Tue Nov 27 21:58:01 GMT 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
Exception in thread "main" java.lang.RuntimeException: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/glassfish/javax/el/main/module.xml
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:89)
	at org.jboss.modules.ModuleLoader.findModule0(ModuleLoader.java:684)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:677)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:487)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:390)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1355)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1403)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1403)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1403)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1403)
	at org.jboss.modules.Module.addPaths(Module.java:1247)
	at org.jboss.modules.Module.link(Module.java:1574)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1602)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:287)
	at org.wildfly.swarm.Swarm.<init>(Swarm.java:220)
	at org.wildfly.swarm.Swarm.<init>(Swarm.java:192)
	at org.wildfly.swarm.Swarm.<init>(Swarm.java:179)
	at org.wildfly.swarm.Swarm.main(Swarm.java:739)
Caused by: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/glassfish/javax/el/main/module.xml
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:298)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:65)
	... 17 more
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'org.glassfish:javax.el-impl:3.0.1-b08-jbossorg-1' (position: END_TAG seen ...artifact name="org.glassfish:javax.el-impl:3.0.1-b08-jbossorg-1"/>... @7:72) 
	at org.jboss.modules.xml.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:953)
	at org.jboss.modules.xml.ModuleXmlParser.parseResources(ModuleXmlParser.java:854)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:645)
	at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:416)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:296)
	... 18 more
```

**Comment by chanseokoh** [comment]
Hi @magick93,

I don't really know anything about Thorntail Microprofile, but I guess your project must be creating a fat jar (`target/demo-thornatil.jar`) and a WAR (`target/demo.tar`).

1. Currently, Jib does not support packaging and running a JAR. Related issues: #530 #1194. It's actually our intention that Jib adds individual class files and dependencie JARs into the container instead of putting a runnable JAR into the container. A [comment](https://github.com/GoogleContainerTools/jib/issues/530#issuecomment-404204465) from #530 explains our intention more or less:
   > A lot of the packaging craziness that frameworks have been doing to have runnable jar services becomes unnecessary with jib. The docker image becomes the package, and we can optimally lay out the application files and configure the entrypoint without any hackery.

1. If you don't really have to containerize a runnable fat JAR, you may opt to containerize a WAR. Your packaging type is WAR (`<packaging>war</packaging>`), so staring from Jib 0.10.0, Jib will identify your project as a WAR project. That said, you need to upgrade to Jib 0.10.0. Then Jib will containerize your WAR with Jetty by default. However, I see you want to use MicroProfile, and I think it's possible to configure Jib to use a MicroProfile base image in this case. See this [doc](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#war-projects) for help (if you are fine with deploying a WAR instead of containerizing a runnable JAR).

**Comment by chanseokoh** [comment]
Just documenting what I tried with a default Thorntail demo app generated from https://thorntail.io/generator/ and containerizing using [Payara Micro](https://www.payara.fish/software/payara-server/payara-micro/) (which claims compatible with MicroProfile):

Working Jib configuration:
```xml
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>0.10.0</version>
        <configuration>
          <from><image>payara/micro:5.183</image></from>
          <to><image>...</image></to>
          <container>
            <appRoot>/my-app</appRoot>
            <args>
              <arg>--deploy</arg>
              <arg>/my-app</arg>
            </args>
          </container>
        </configuration>
```

`localhost:8080/my-app/hello` will greet the visitor.

If needed to deploy to the root context, one way I found is to have `glassfish-web.xml` under `src/main/webapp/WEB-INF` like this:
```xml
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD 
GlassFish Application Server 3.1 Servlet 3.0//EN"
"http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app>
  <context-root>/</context-root>
</glassfish-web-app>
```
Then `localhost:8080/hello` will greet the visitor.

**Comment by chanseokoh** [comment]
Closing this in favor of #1857.

Deploying a WAR is another option.
