### ISSUE TITLE
Additional tag regex unusually strict

### ISSUE THREAD

**Issue by timtebeek** [GoogleContainerTools/jib#1420]
At our company we tag our Docker images with quite a few long tags, which are later used in deployments. Sample tags without Jib come from:
```
docker build \
  -t registry.example.org/project-name:master-1234 \
  -t registry.example.io/project-name:master-1234 \
  -t registry.example.org/project-name:latest \
  -t registry.example.io/project-name:latest \
  .
```

**Description of the issue**:
When I try to switch to Jib for image generation and tagging, I get an exception when running `gradle jibDockerBuild` on the tag validation regex.

**Expected behavior**:
Tags containing semicolons and slashes are allowed.

**Steps to reproduce**:
Provide additional tags with non word characters, as outlined below.

**Environment**: Linux, Gradle

**`jib-gradle-plugin` Configuration**:
```groovy
jib {
  from {
    image = 'some/image'
  }
  to {
    image = "registry.example.org/project-name:master-1234"
    tags = [
        "registry.example.io/project-name:master-1234",
        "registry.example.org/project-name:latest",
        "registry.example.io/project-name:latest",
    ]
  }
```

**Log output**: 
```
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:121)
	at com.google.cloud.tools.jib.api.Containerizer.withAdditionalTag(Containerizer.java:107)
	at com.google.cloud.tools.jib.plugins.common.PluginConfigurationProcessor.configureContainerizer(PluginConfigurationProcessor.java:455)
	at com.google.cloud.tools.jib.plugins.common.PluginConfigurationProcessor.processCommonConfiguration(PluginConfigurationProcessor.java:224)
```

**Additional Information**:
[Looking at the source](https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java#L65) I see the regex for tag validation is currently set to: `TAG_REGEX = "[\\w][\\w.-]{0,127}"`.

This seems unusually strict, as there's a lot more tag formats in common use:
https://stackoverflow.com/questions/39671641/regex-to-parse-docker-tag

Can the validation of allowed additional tags be adapted to allow for these extended formats? Or is there something wrong with my setup/expectations? Would also accept any workarounds, such as pushing the tags separately, but it seems odd these formats are not allowed.

**Comment by coollog** [comment]
Hi @timtebeek , we are actually referring to tags in the image reference terminology, where `tag` refers to the portion in the image reference after the colon. 

For example, for the image reference `registry.example.io/project-name:master-1234`, the `tag` portion is `master-1234`, whereas `registry.example.io` is the registry portion and `project-name` is the repository portion.

Jib's `tags` configuration only allows for pushing to additional tags in the same registry/repository. Jib does not currently support pushing to multiple repositories in its own configuration, but you can definitely define separate executions in Gradle with different `to.image`s.

**Comment by briandealwis** [comment]
> Tags containing semicolons and slashes are allowed.

 And just in case, [image references / tags do not allow for semicolons](https://docs.docker.com/engine/reference/commandline/tag/#extended-description).
