### ISSUE TITLE
Better actionable error message on InvalidImageReferenceException: Invalid image reference

### ISSUE THREAD

**Issue by senyo-asamoah-zefr** [GoogleContainerTools/jib#1577]
**Description of the issue**:
An uncheckedException, InvalidImageReferenceException, when pushing to an gcr

**Expected behavior**:
Should be able to successfully push new image to remote gcr

**Steps to reproduce**: 
* add the jib gradle plugin
* configure the jib plugin to push image to gcr
* run a gradle jib

**Environment**: 
Gradle, MacOS

**`jib-gradle-plugin` Configuration**: 
```groovy
jib{
    from{
        image = 'openjdk:11-jre-slim'
    }
    to{
        image = "gcr.io/****/$rootProject.name"
    }
    container{
        jvmFlags = ['-Xdebug']
        ports = ['8181']
    }
}
```

```
Caused by: org.gradle.internal.UncheckedException: com.google.cloud.tools.jib.image.InvalidImageReferenceException: Invalid image reference: gcr.io/***/my_app_name
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:106)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:672)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:338)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:327)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:312)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:15
```

**Comment by chanseokoh** [comment]
Hi @senyo-asamoah-zefr,

According to the Docker [doc](https://docs.docker.com/engine/reference/commandline/tag/),

> Name components may contain lowercase letters, digits and separators.

You should not put uppercase letters.

**Comment by senyo-asamoah-zefr** [comment]
Hi @chanseokoh 
Thanks so much for pointing this out, i totally missed that part, changing the project name worked.

**Comment by chanseokoh** [comment]
We will think about surfacing the cause of the invalid format.

**Comment by senyo-asamoah-zefr** [comment]
that will be great, i can submit a PR for this

**Comment by chanseokoh** [comment]
We haven't thought about what the error message should be to be more informative and actionable. Maybe more descriptive and some ideas is to show a valid regex, show a doc link, or link to this issue. We'd appreciate your PR anyway. Thanks!
