### ISSUE TITLE
using jib-core can't push images into Sonatype Nexus registry

### ISSUE THREAD

**Issue by Lionelpang** [GoogleContainerTools/jib#1578]
Using jib-core to push and mirror images into the private repository of [nexus](https://www.sonatype.com/download-oss-sonatype), 

the code is as follows:
```
EventHandlers eventHandlers = new EventHandlers()
                .add(JibEventType.LOGGING, logEvent -> System.out.println(logEvent.getLevel() + ": " + logEvent.getMessage()));
        Jib.from(RegistryImage.named("192.168.3.151:18082/busybox:latest").addCredential("admin", "admin123"))
                .addLayer(Arrays.asList(Paths.get("helloworld.sh")), AbsoluteUnixPath.get("/"))
                .containerize(
                        Containerizer.to(
                                RegistryImage.named("192.168.3.151:18082/lionel-test")
                                .addCredential("admin", "admin123")
                        ).setAllowInsecureRegistries(true).setEventHandlers(eventHandlers)
                );
```

But the following errors were reported：
com.google.cloud.tools.jib.registry.RegistryCredentialsNotSentException: Required credentials for 192.168.3.151:18082/lionel-test were not sent because the connection was over HTTP
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:276)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.fallBackToHttp(RegistryEndpointCaller.java:191)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.handleUnverifiableServerException(RegistryEndpointCaller.java:180)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.callWithAllowInsecureRegistryHandling(RegistryEndpointCaller.java:155)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:142)
	at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:356)
	at com.google.cloud.tools.jib.registry.RegistryClient.pushBlob(RegistryClient.java:304)
	at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:124)
	at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:40)
	at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:180)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
How to solve this problem?

**Description of the issue**:

**Expected behavior**:

**Steps to reproduce**: 

**Environment**: 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by Lionelpang** [comment]
System.setProperty(JibSystemProperties.SEND_CREDENTIALS_OVER_HTTP, "true"); 
Solve
