### ISSUE TITLE
Integration test failing probably after adding extra classpath

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1663]
```
com.google.cloud.tools.jib.gradle.SingleProjectIntegrationTest > testDockerDaemon_simpleOnJava11 SKIPPED

com.google.cloud.tools.jib.gradle.SingleProjectIntegrationTest > testBuild_simple FAILED
    org.junit.ComparisonFailure: expected:<[java -cp /[d1:/d2:/]app/resources:/app/c...> but was:<[java -cp /[]app/resources:/app/c...>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.google.cloud.tools.jib.gradle.SingleProjectIntegrationTest.assertEntrypoint(SingleProjectIntegrationTest.java:82)
        at com.google.cloud.tools.jib.gradle.SingleProjectIntegrationTest.testBuild_simple(SingleProjectIntegrationTest.java:196)

com.google.cloud.tools.jib.gradle.SingleProjectIntegrationTest > testDockerDaemon_simpleWithIncompatibleJava11 SKIPPED
```

**Comment by briandealwis** [comment]
Odd, I'm not sure how the tests passed earlier?  There are two `simple` test projects in `jib-gradle-plugin`: one in `src/test/resources/gradle/projects` and the other in `src/integration-test/resources/gradle/projects`.
