### ISSUE TITLE
JibDockerBuild Failed

### ISSUE THREAD

**Issue by joshisagar92** [GoogleContainerTools/jib#1710]
Hello,
We are getting following error while creating docker image through jib gradle plugin.
Gradle Version 4.10.3
Jib Gradle Plugin Version:1.2.0
We have added Guava as compile time dependency in build.gradle to support legacy code. 

Cause: method not found com.google.common.collect.Range.atLeast(Ljava/lang/Comparable;)Lcom/google/common/collect/Range;

**Comment by loosebazooka** [comment]
Looks like a guava incompatibility issue. Are you using other plugins with
your build?

*From: *Sagar Joshi <notifications@github.com>
*Date: *Fri, May 10, 2019, 08:33
*To: *GoogleContainerTools/jib
*Cc: *Subscribed

Hello,

**Comment by chanseokoh** [comment]
I suspect the Guava compile-time dependency you added is used in Gradle builds too. There's a way to have builds use (or force to use) a different Guava version by defining it in `buildscript`. See https://github.com/GoogleContainerTools/jib/issues/1390#issuecomment-451286883, https://github.com/GoogleContainerTools/jib/issues/1390#issuecomment-451313509 and https://github.com/GoogleContainerTools/jib/issues/591#issuecomment-478027065 (Kotlin) for examples. The Guava version Jib uses is `27.0.1-jre`. Try that and let us know.

**Comment by loosebazooka** [comment]
The compile time dependencies, and build dependencies are two different classloaders. So the process that is doing your build is the one that probably has the conflict (not guava included as part of your application). Can you show us your buildscript and plugins blocks?

**Comment by joshisagar92** [comment]
Following is my gradle configuration file. Jar file of Guava we have added in file tree src/main/webapp/WEB-INF/lib. I am still getting the same error.

group 'XXX'
version 'XXX'
buildscript {
    repositories {
        mavenCentral()
    }
   dependencies {
		classpath("com.google.guava:guava:27.0.1-jre"){
			force = true
		}
     }
}
plugins {
	id 'org.liquibase.gradle' version '1.2.1'
	id 'com.google.cloud.tools.jib' version '1.2.0'
}

apply plugin: 'groovy'
apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'eclipse-wtp'
apply plugin : 'jacoco'

jib {
	from {
		image = 'tomcat:8.5'
	}
	container {
		appRoot = '/usr/local/tomcat/webapps/app'
		ports = ['8085/tcp']
		useCurrentTimestamp = true
	}
	to {
		image = 'mydomain.com/build1.1:latest'
	}
	allowInsecureRegistries = true
}

compileJava.options.encoding = 'ISO-8859-1'

sourceCompatibility = 1.7

repositories {
	mavenCentral()
	maven {
		url "http://repo.fusesource.com/nexus/content/groups/public/"
	}
	maven {
		url "https://repository.jboss.org/nexus/content/groups/public"
	}
	jcenter()
}



dependencies {

	compile group: 'org.json', name: 'json', version: '20160212'
	compile group: 'io.jsonwebtoken', name: 'jjwt', version: '0.7.0'

	compile fileTree(dir: 'src/main/webapp/WEB-INF/lib', include: '*.jar' )
}

**Comment by loosebazooka** [comment]
Can you try including the guava dependency using it's coordinates?
```
compile "com.google.guava:guava:<version>"
```

If the issue still persists, can you provide a more detailed error log? It's really hard to tell at what step the 
error is occuring, maybe use `--console=plain` when you run the build.

**Comment by joshisagar92** [comment]
I have tried that as well, but it did not work.

It throws following error:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jibDockerBuild'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Range.atLeast(Ljava/lang/Comparable;)Lcom/google/common/collect/Range;
        at com.google.cloud.tools.jib.global.JibSystemProperties.checkHttpTimeoutProperty(JibSystemProperties.java:87)
        at com.google.cloud.tools.jib.plugins.common.PluginConfigurationProcessor.processCommonConfiguration(PluginConfigurationProcessor.java:162)
        at com.google.cloud.tools.jib.plugins.common.PluginConfigurationProcessor.processCommonConfigurationForDockerDaemonImage(PluginConfigurationProcessor.java:81)
        at com.google.cloud.tools.jib.gradle.BuildDockerTask.buildDocker(BuildDockerTask.java:119)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more

**Comment by loosebazooka** [comment]
Sorry, I meant your dependency in `webapp/WEB-INF/lib`, but that doesn't seem to be the problem? Do you have a parent build file? Is this part of a multi module project?

**Comment by loosebazooka** [comment]
I've tried something similar to your build with all the same plugins and gradle version and I just can't hit this error.

**Comment by joshisagar92** [comment]
Thanks for continuous support. 
Issue is resolved, Somehow it was conflicting from buildSrc's build.gradle file.
After adding

`compile "com.google.guava:guava:27.0.1-jre"` in dependency of buildSrc's build.gradle issue resolved.
Thanks.
