### ISSUE TITLE
Test failure about root progress dispatch

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1796]
This looks like a flaky test, but I don't remember having seen this. It means the progress event dispatched more completion than the total expected. It's concerning, so I'll dig into it.

```
    * What went wrong:
    Execution failed for task ':jibDockerBuild'.
    > Progress exceeds max for 'building image to Docker daemon': 1 more beyond 5

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 4s
    3 actionable tasks: 3 executed
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:237)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:234)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:298)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:234)
        at com.google.cloud.tools.jib.gradle.TestProject.build(TestProject.java:82)
        at com.google.cloud.tools.jib.gradle.JibRunHelper.buildToDockerDaemon(JibRunHelper.java:96)
        at com.google.cloud.tools.jib.gradle.EmptyProjectIntegrationTest.testDockerDaemon_userNames(EmptyProjectIntegrationTest.java:112)
```

**Comment by chanseokoh** [comment]
Ah, fortunately, this seems like the failure only at the `rootProgressDescription` level.

```
> Progress exceeds max for 'building image to registry': 1 more beyond 10
```

```
 > Progress exceeds max for 'building image to Docker daemon': 1 more beyond 5
```
