### ISSUE TITLE
Flaky test about progress footer display

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1839]
From Kokoro Mac presubmit.

I've never seen this. I think this is a rare failure. Worth looking into it though.

```
com.google.cloud.tools.jib.plugins.common.logging.AnsiLoggerWithFooterTest > testLog_sameFooter FAILED
    java.lang.AssertionError: expected:<[footer, , message, footer, , another message, footer]> but was:<[footer, , message, footer]>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.google.cloud.tools.jib.plugins.common.logging.AnsiLoggerWithFooterTest.testLog_sameFooter(AnsiLoggerWithFooterTest.java:130)
```

**Comment by chanseokoh** [comment]
Fortunately, there is nothing critical to worry about this failure.

I think this happens when `SingleThreadedExecutor.awaitTermination()` times out (similar to the cause in #1846). I can reproduce this with a high probability when I set the timeout to 0 locally. I'll increase the timeout as in #1846.
