### ISSUE TITLE
Flaky test: testSyncMapMojo_failIfWar()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2209]
This failed on the Travis Oracle JDK 8 build while the OpenJDK 11 build succeeded. So I think this is a flaky test. I am not sure how this failed.

```
com.google.cloud.tools.jib.gradle.JibPluginTest > testCheckGradleVersion_pass STANDARD_OUT
    Downloading https://services.gradle.org/distributions/gradle-4.9-bin.zip
    ........................................................................
com.google.cloud.tools.jib.gradle.skaffold.SyncMapTaskTest > testSyncMapMojo_failIfWar FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at com.google.cloud.tools.jib.gradle.skaffold.SyncMapTaskTest.testSyncMapMojo_failIfWar(SyncMapTaskTest.java:159)
56 tests completed, 1 failed, 1 skipped
```

**Comment by chanseokoh** [comment]
I think Maven Central is unstable today.
