### ISSUE TITLE
Support for Gradle Configuration Cache

### ISSUE THREAD

**Issue by Fabian-K** [GoogleContainerTools/jib#3132]
**Environment**:

- *Jib version:* 2.8.0
- *Build tool:* Gradle 6.8.1
- *OS:* Mac

**Description of the issue**:

Gradle 6.8 has a new configuration cache feature that helps to improve build performance. Unfortunately, there are some restrictions on what plugins can use and jib is currently not compatible with this. I don´t think that jib, in particular, is bad wrt to build performance, still, I think it would be cool if it supports the configuration cache at some point :)

**Steps to reproduce**:
  1.  `gradle --configuration-cache jib`
 
**Log output**: 
```
- Task `:html5-controller:jib` of type `com.google.cloud.tools.jib.gradle.BuildImageTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/6.8.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:html5-controller:jib` of type `com.google.cloud.tools.jib.gradle.BuildImageTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/6.8.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

**Comment by chanseokoh** [comment]
Interesting. Thanks for the feedback! Sounds like a new feature in the latest Gradle? For now, I added the "help wanted" label.

**Comment by ssp** [comment]
Any news about this one? Many Gradle plugins have embraced the configuration cache by now and jib would be a great addition to that as it seems quite essential for today’s container-centric builds.

I tried to dig into this myself but got the impression that the design of the plugin relies on getting hold of the `Project` object at various times of the build. Unfortunately my understanding of the jib plugin’s working isn’t sufficient to see an obvious way of fixing that.

Essentially using the configuration cache requires the `Project` (and other Gradle objects) not to be accessed at build time but only at configuration time. https://docs.gradle.org/7.3.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

The report generated by Gradle 7.3.1 for running `jibDockerBuild`, for example, contains these pointers

![jib-build-cache](https://user-images.githubusercontent.com/40549/145986395-4b7dca79-adc2-435b-8fc7-2efc3ba69c46.png)

and throws an Exception at

```
org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':fulfill:reporting:jibDockerBuild' at execution time is unsupported.
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onTaskExecutionAccessProblem(ConfigurationCacheProblemsListener.kt:75)
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onProjectAccess(ConfigurationCacheProblemsListener.kt:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:464)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:446)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:61)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:434)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:221)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:192)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy117.onProjectAccess(Unknown Source)
	at org.gradle.api.internal.AbstractTask.notifyProjectAccess(AbstractTask.java:1020)
	at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:228)
	at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
	at com.google.cloud.tools.jib.gradle.BuildDockerTask.buildDocker(BuildDockerTask.java:110)
```

**Comment by egaga** [comment]
Any news on this?

**Comment by wwadge** [comment]
If you're in need of workaround:

```
['jibDockerBuild', 'jibBuildTar', 'jib'].each { taskName ->
    getTasksByName(taskName, true).each(it -> {
        it.notCompatibleWithConfigurationCache("Jib is not compatible with configuration cache");
         }); }```

**Comment by gavvvr** [comment]
Even more concise and type-safe workaround for now:
```kotlin
import com.google.cloud.tools.jib.gradle.JibTask
// ...
tasks.withType<JibTask> {
    notCompatibleWithConfigurationCache("because https://github.com/GoogleContainerTools/jib/issues/3132")
}
```

**Comment by simondemartini** [comment]
Since this was last updated, it looks like [Gradle announced that they will deprecate disabling of the configuration cache in Gradle 9](https://blog.gradle.org/road-to-gradle-9#configuration-cache-improvements).

> In Gradle 9.0, the Configuration Cache will be the preferred mode of execution, and turning it off will be deprecated.

Is this something this project has plans to support sooner than later?

**Comment by nbrugger-tgm** [comment]
If I get the go from my company to spend time on this i will implement this

**Comment by sschuberth** [comment]
> If I get the go from my company to spend time on this i will implement this

That's great to hear, however there already are multiple unmerged PRs to address the issue. So the problem is not the implementation per se, but the fact that Google "[[does not] want to introduce a breaking change for customers still use Gradle < 8 at this moment](https://github.com/GoogleContainerTools/jib/pull/4139#issuecomment-1894412755)". Bummer.

**Comment by yogurtearl** [comment]
It is possible to provide variants of the plugin to support older versions of gradle: 

https://docs.gradle.org/8.13/userguide/implementing_gradle_plugins_binary.html#plugin-with-variants

**Comment by nbrugger-tgm** [comment]
Also isn't it possible to do this without changing userfacing apis?

If i recall correctly the issue is that project or some forbidden instance is dragged through most extensions which is internal/implementation detail imo

Which breaking changes would be required to adapt the plugin to be compliant

**Comment by sschuberth** [comment]
> > If I get the go from my company to spend time on this i will implement this
> 
> That's great to hear, however there already are multiple unmerged PRs to address the issue. So the problem is not the implementation per se, but the fact that Google "[[does not] want to introduce a breaking change for customers still use Gradle < 8 at this moment](https://github.com/GoogleContainerTools/jib/pull/4139#issuecomment-1894412755)". Bummer.

So, would it be fair to remove the "help wanted" label from this issue to prevent contributors to spend time on solutions that won't get reviewed / merged by Google anyway?

**Comment by nbrugger-tgm** [comment]
Yes please - while i currently maintain a fork for myself, this is a bit painful since i originally wanted to create a PR. How can we get a maintainer to close (with reason) or otherwise update the issue?

**Comment by martinbonnin** [comment]
@nbrugger-tgm is your fork published? I would use that.

**Comment by zapodot** [comment]
Any chance of this making its way in to a release any time soon?

**Comment by pschichtel** [comment]
I've build [a small version of the gradle plugin](https://plugins.gradle.org/plugin/tel.schich.tinyjib) that is fully configuration cache compatible. It uses basically the same logic as this plugin for dependency resolution, but moves the necessary steps to the configuration phase. There were also a few other more subtle things incompatible with configuration caching (and/or with future gradle versions).

**Comment by haakonrp** [comment]
Any updates on this?
