### ISSUE TITLE
[Jib CLI] --http-trace sometimes doesn't work

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#3156]
The behavior is very unpredictable. That makes me suspect a concurrency issue. And it seems to always work with `--serialize`.

**Comment by chanseokoh** [comment]
So I put debugging statements to print the level of `HttpTransport` logger in multiple places.
```
      System.out.println("#1 " + Logger.getLogger(HttpTransport.class.getName()).getLevel());
```
When the issue happens, at some point the level becomes `null`. In the log below, it was the 7th check, but I've seen becoming `null` at earlier times.
```
#1 CONFIG
#2 CONFIG
[WARN] Base image 'adoptopenjdk:8-jre' does not use a specific image digest - build may not be reproducible
#3 CONFIG
#4 CONFIG
#5 CONFIG
#6 CONFIG
Getting manifest for base image adoptopenjdk:8-jre...
Building dependencies layer...
Using credentials from Docker config (/home/chanseok/.docker/config.json) for openjdk
Building classes layer...
Building resources layer...
The base image requires auth. Trying again for adoptopenjdk:8-jre...
#7 null
```
Certainly concurrency is affecting the issue.

**Comment by chanseokoh** [comment]
I poked around the JDK JUL `Logger` code and tried to see who may be manipulating the `HttpTransport` logger.

So, in a non-main thread (thread #14), when `ApacheHttpTransport` seemed to be accessed for the first time, `Logger.getLogger(HttpTransport)` is called.
```
Using credentials from Docker config (/home/chanseok/.docker/config.json) for openjdk
T14 pool-2-thread-1
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at java.util.logging.Logger.demandLogger(Logger.java:449)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at com.google.api.client.http.HttpTransport.<clinit>(HttpTransport.java:73)
	at com.google.cloud.tools.jib.http.FailoverHttpClient.getSecureHttpTransport(FailoverHttpClient.java:102)
	at com.google.cloud.tools.jib.http.FailoverHttpClient.getHttpTransport(FailoverHttpClient.java:335)
	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:250)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:115)
	at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:624)
	at com.google.cloud.tools.jib.registry.RegistryClient.doBearerAuth(RegistryClient.java:320)
	at com.google.cloud.tools.jib.registry.RegistryClient.doPushBearerAuth(RegistryClient.java:310)
	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:66)
	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:1)
```

Indeed, a static `LOGGER` field is being initialized.
```java
public abstract class HttpTransport {

  static final Logger LOGGER = Logger.getLogger(HttpTransport.class.getName());
```

And with some experiments, I noticed that, probably `Logger.getLogger()` is called for a given class for the first time, it goes into this chain that reads configuration (from multiple external sources like a JUL config file and properties) and initializes it, which includes calling `reset()` and `setLevel()`.
```
	at java.util.logging.Logger.setLevel(Logger.java:1689)
	at java.util.logging.LogManager.resetLogger(LogManager.java:1356)
	at java.util.logging.LogManager.reset(LogManager.java:1332)
	at java.util.logging.LogManager.readConfiguration(LogManager.java:1406)
	at java.util.logging.LogManager.readConfiguration(LogManager.java:1303)
	at java.util.logging.LogManager$3.run(LogManager.java:399)
	at java.util.logging.LogManager$3.run(LogManager.java:396)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at java.util.logging.Logger.demandLogger(Logger.java:448)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at com.google.api.client.http.HttpTransport.<clinit>(HttpTransport.java:73)
```
So I suspect that after we set the log level for `HttpTransport` in `JibCli` in the following way, 
```java
    Logger logger = Logger.getLogger(HttpTransport.class.getName());
    logger.setLevel(level);
```
the logger for `HttpTransport` becomes re-initialized when an `HttpTransport` instance is created for the first time due to the statically initializer for `HttpTransport.LOGGER`. (And I verified that simply calling `HttpTransport.clas.getName()` in `JibCli` doesn't trigger the static initializer.) Or, it could be that `Logger.getLogger()` in `JibCli` and `HttpTransport` end up using different logger instances.

In any case, it appears that there is a race condition. I think the problem arises because we configure the logger in one thread, but the `HttpTransport.LOGGER` is initialized for the first time in another thread concurrently.

With this theory, the solution is to simply initialize `HttpTransport.LOGGER` before we set the logging level, eliminating the race condition.

**Comment by chanseokoh** [comment]
Oh, actually, the Javadoc of `Logger.getLogger()` says this, and this may be the cause:
```
     * Note: The LogManager may only retain a weak reference to the newly
     * created Logger. It is important to understand that a previously
     * created Logger with the given name may be garbage collected at any
     * time if there is no strong reference to the Logger. In particular,
     * this means that two back-to-back calls like
     * {@code getLogger("MyLogger").log(...)} may use different Logger
     * objects named "MyLogger" if there is no strong reference to the
     * Logger named "MyLogger" elsewhere in the program.
```
In any case, because `HttpTransport` holds the logger as a static variable, so #3157 will fix the issue.
