### ISSUE TITLE
Failing to pull/push image due to missing method on google http java client

### ISSUE THREAD

**Issue by fanonxr** [GoogleContainerTools/jib#3282]
**Environment**: IntellIJ, java version 1.8, local env

- *Jib version:*  0.18.0
- *Build tool:* Maven
- *OS:* Mac OS Catalina

**Description of the issue**:

I'm getting an error when attempting to pull from one cloud registry to another. The error seems to stem from the google http java client that is using does not have a particular method to pull the image from a registry. 

Here is my code:

```
/*
* Generate random text - we use this random generated text to change the sha-256 digest to signify that its a new image
* */
private void generateRandomText() {
    //generate random 4 KB of data and write them to a file
    String uid = UUID.randomUUID().toString();
    try (RandomAccessFile f = new RandomAccessFile(RANDOM_TEXT, "rw")) {
        // an UUID is 36 bytes times 113 makes 4KB
        f.writeBytes(String.join("", Collections.nCopies(113, uid)));
    } catch (IOException e) {
        e.printStackTrace();
    }
}


/**
 * pull and push an image from one registry to another
 * @param fromRegistry - the registry we will be pushing the image from
 * @param toRegistry - the registry we will push the image to
 * */
public void pullAndPushImageToRegistry(String fromRegistry, String toRegistry) {
    generateRandomText();
    try {
        Jib.from(ImageReference.parse(fromRegistry))
                .addLayer(Arrays.asList(Paths.get(RANDOM_TEXT)), AbsoluteUnixPath.get("/"))
                .containerize(
                        Containerizer.to(RegistryImage.named(toRegistry)
                                .addCredential("username","password")));
    } catch (InterruptedException | RegistryException | IOException | CacheDirectoryCreationException | ExecutionException | InvalidImageReferenceException e) {
        LOG.error("Failed to push image " + e.getMessage());
        //e.printStackTrace();
    }
}
```

here is the error: 
```
Failed to push image java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setUseRawRedirectUrls(Z)Lcom/google/api/client/http/HttpRequest;
```

**Expected behavior**:

The expected behavior is to pull from one registry and push to another. I've noticed though if I use 
`jib.fromScratch()` instead of `jib.from(imageRef.parse(fromRegistry))` I'm able to successfully push a empty base image. 

**Steps to reproduce**:

  1.  Simple just made a class with the above methods
  2. made a quick Main class to test this by passing in valid registry urls: `pullAndPushImageToRegistry(otherregistry.azurecr.io/samples/nginx, myregistry.azurecr.io/samples/nginx)`

**Log output**: 
fullstack trace if this helps 
```
09:06:31.654 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager is shutting down
09:06:31.656 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager shut down
09:06:31.656 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager is shutting down
09:06:31.656 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager shut down
09:06:31.656 [main] ERROR com.oracle.pic.ociapp.cp.worker.util.jib.JibClientImpl - Failed to push image java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setUseRawRedirectUrls(Z)Lcom/google/api/client/http/HttpRequest;
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setUseRawRedirectUrls(Z)Lcom/google/api/client/http/HttpRequest;
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:88)
	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$obtainBaseImagesLayers$6(StepsRunner.java:313)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setUseRawRedirectUrls(Z)Lcom/google/api/client/http/HttpRequest;
	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:315)
	at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:250)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:115)
	at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:624)
	at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:436)
	at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:441)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImages(PullBaseImageStep.java:290)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:157)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:69)
	... 6 more
```

**Comment by mpeddada1** [comment]
Hi, your project seems to be pulling in an older version of google http java client. Looks like @chanseokoh already responded to your [Stackoverflow question](https://stackoverflow.com/questions/67864804/pull-image-from-one-registry-in-the-cloud-and-push-to-another-registry-in-the-cl).

**Comment by elharo** [comment]
Make sure you're using google-http-java-client 1.34.1 or later. 1.34.0 would probably work too, but best is to use the latest, 1.39.2.

**Comment by fanonxr** [comment]
Okay thanks! that did the trick.
