### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: 'void org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(java.nio.file.Path, java.lang.String, java.nio.file.LinkOption[])'

### ISSUE THREAD

**Issue by zgqq** [GoogleContainerTools/jib#3794]
**Environment**:

- *Jib version:* 3.3.0
- *Build tool:* gradle 7.3.1 
- *OS:* macOS 15.5.1

**Description of the issue**:
Executing ./gradlew jib
```
Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: 'void org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(java.nio.file.Path, java.lang.String, java.nio.file.LinkOption[])'
        at com.google.cloud.tools.jib.plugins.common.JibBuildRunner.runBuild(JibBuildRunner.java:285)
        at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:122)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ... 114 more
Caused by: java.lang.NoSuchMethodError: 'void org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(java.nio.file.Path, java.lang.String, java.nio.file.LinkOption[])'
        at com.google.cloud.tools.jib.image.ReproducibleLayerBuilder.build(ReproducibleLayerBuilder.java:154)
        at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:107)
        at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:38)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
```
**There is no the problem using 3.1.0 or 3.0.0.**

**Steps to reproduce**:

  1.
  ```
plugins {
    id 'com.google.cloud.tools.jib' version '3.3.0'
}
```
   2. Composite build
 includeBuild './lib-flycat'  

  

**Log output**: 

**Additional Information**:

**Comment by emmileaf** [comment]
The `org.apache.commons.compress` library dependency has had a version upgrade from 1.20 to 1.21 since Jib 3.1.0, and I wonder if an older version is somehow getting pulled in here? [This section in the FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-seeing-method-not-found-or-class-not-found-errors-when-building) might be of help with working around the dependency version mismatch issue.

**Comment by zgqq** [comment]
@emmileaf The problem was issused, caused by a plugin that is no longer maintained.
```
id "net.rdrei.android.buildtimetracker" version "0.11.0" 
```
It's ok after removing it .
