### ISSUE TITLE
Long time taken when a large subdirectory is used as a recursive layer

### ISSUE THREAD

**Issue by sameergn** [GoogleContainerTools/jib#3801]
**Environment**:

- *Jib version:* 0.22
- *Build tool:* Gradle 
- *OS:* Linux

**Description of the issue**:
We are adding a large sub-directory as a layer (~234MB)
Jib seems to build this layer locally even though it is cached locally and this operation takes around 25 seconds.
`2022-09-29 00:28:25,133 sn:]  - Jib Builder Log [DEBUG]: Building  layer built sha256:a5ca6eb638e9710574d074247f77b640c0b1d86942c5e0fb1deaf3452325a7cb`
This process takes about 25 seconds, then it says that layer already exists
`2022-09-29 00:28:25,456 sn:]  - Jib Builder Log [INFO]: Skipping push; BLOB already exists on target registry : digest: sha256:a5ca6eb638e9710574d074247f77b640c0b1d86942c5e0fb1deaf3452325a7cb, size: 234630578`

```
bash-4.2$ find /tmp/jib_image_cache/ -name a5ca6eb638e9710574d074247f77b640c0b1d86942c5e0fb1deaf3452325a7cb -exec ls -lrt {} \;
total 229132
-rw-r----- 1 tomcat tomcat 234630578 Sep 29 00:28 7161988df87ff3006f5803117549fb6d14109073edfcde7b2d0d549dc706ad94

bash-4.2$ find /tmp/jib_image_cache/ -name a5ca6eb638e9710574d074247f77b640c0b1d86942c5e0fb1deaf3452325a7cb -exec ls -lrtd {} \;
drwx------ 3 tomcat tomcat 90 Sep 29 06:56 /tmp/jib_image_cache/layers/a5ca6eb638e9710574d074247f77b640c0b1d86942c5e0fb1deaf3452325a7cb
```

**Expected behavior**:
Is there any way to speed up the process?
There are 680 files in 38 sub directories under main directory.
Is it a good idea to add each sub directory or file as a layer?

**Comment by sameergn** [comment]
Here is the thread dump analysis from 17 thread dump files taken each 1 seconds apart
```
$ grep -h jib td_2[5-9].txt td_3*.txt td_40.txt | sort | uniq -c | sort -n
     16 	at com.google.cloud.tools.jib.api.Containerizer.run(Containerizer.java:406)
     16 	at com.google.cloud.tools.jib.api.JibContainerBuilder.containerize(JibContainerBuilder.java:610)
     16 	at com.google.cloud.tools.jib.blob.FileBlob.writeTo(FileBlob.java:39)
     16 	at com.google.cloud.tools.jib.blob.WritableContentsBlob.writeTo(WritableContentsBlob.java:37)
     16 	at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:108)
     16 	at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:38)
     16 	at com.google.cloud.tools.jib.builder.steps.PushLayerStep.call(PushLayerStep.java:33)
     16 	at com.google.cloud.tools.jib.builder.steps.PushLayerStep.call(PushLayerStep.java:78)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner$$Lambda$813/1096645609.call(Unknown Source)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner$$Lambda$817/1731439084.call(Unknown Source)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner$$Lambda$818/794482952.call(Unknown Source)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner$$Lambda$819/144981830.call(Unknown Source)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner$$Lambda$846/1634913919.call(Unknown Source)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner$$Lambda$847/1376587332.call(Unknown Source)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$buildImage$9(StepsRunner.java:450)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$buildManifestListOrSingleManifest$10(StepsRunner.java:462)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$checkManifestInTargetRegistry$14(StepsRunner.java:524)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$pushContainerConfiguration$12(StepsRunner.java:499)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$pushImages$15(StepsRunner.java:537)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$pushManifestList$17(StepsRunner.java:597)
     16 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.run(StepsRunner.java:219)
     16 	at com.google.cloud.tools.jib.cache.CacheStorageWriter.writeUncompressed(CacheStorageWriter.java:282)
     16 	at com.google.cloud.tools.jib.cache.CacheStorageWriter.writeUncompressedLayerBlobToDirectory(CacheStorageWriter.java:430)
     16 	at com.google.cloud.tools.jib.cache.Cache.writeUncompressedLayer(Cache.java:144)
     16 	at com.google.cloud.tools.jib.hash.Digests.computeDigest(Digests.java:88)
     16 	at com.google.cloud.tools.jib.hash.Digests$$Lambda$825/221689139.writeTo(Unknown Source)
     16 	at com.google.cloud.tools.jib.hash.Digests.lambda$computeDigest$2(Digests.java:87)
     16 	at com.google.cloud.tools.jib.image.ReproducibleLayerBuilder$$Lambda$824/900389992.writeTo(Unknown Source)
     16 	at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeAsTarArchiveTo(TarStreamBuilder.java:53)
     32 	at com.google.cloud.tools.jib.hash.CountingDigestOutputStream.write(CountingDigestOutputStream.java:80)
     32 	at com.google.cloud.tools.jib.hash.Digests.computeDigest(Digests.java:104)
     48 	at com.google.cloud.tools.jib.builder.steps.StepsRunner.realizeFutures(StepsRunner.java:112)

$ ls -lrt td_2[5-9].txt td_3*.txt td_40.txt | wc -l
17

**Comment by mpeddada1** [comment]
@sameergn Historically we've seen slow builds when using base images from docker hub (See https://github.com/GoogleContainerTools/jib/issues/648 for the full discussion). This is one potential cause I can think of at the moment for the delay you're experiencing.
