### ISSUE TITLE
can not push image to harbor v2.5.4

### ISSUE THREAD

**Issue by k8ses** [GoogleContainerTools/jib#3804]
**Environment**:
- *Jib version:* '3.2.0'
- *OS:* windows10
- *Harbor version:* v2.5.4-a39bd2bc
- *java jar:* com.google.cloud.tools:jib-core:0.19.0
**Description of the issue**:
I upgrade harbor to v2.5.4-a39bd2bc from  v1.10.0-08558d37. I try to push image by java code ( com.google.cloud.tools:jib-core:0.19.0 ).Then there is a error .
```shell
Caused by: com.google.cloud.tools.jib.http.ResponseException: 401 Unauthorized
HEAD http://docker-registry:81/v2/harbor-test/est-image-terminal/blobs/sha256:a59ad170d12952cdf37e97da5e136f8ecae13c166decd724cd040a1a1dff24f9
        at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:329) ~[jib-core-0.19.0.jar:0.19.0]
        at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:265) ~[jib-core-0.19.0.jar:0.19.0]
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139) ~[jib-core-0.19.0.jar:0.19.0]
        ... 12 more
Caused by: com.google.api.client.http.HttpResponseException: 401 Unauthorized
HEAD http://docker-registry:81/v2/harbor-test/test-image-terminal/blobs/sha256:a59ad170d12952cdf37e97da5e136f8ecae13c166decd724cd040a1a1dff24f9
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1113) ~[google-http-client-1.36.0.jar:1.36.0]
        at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:323) ~[jib-core-0.19.0.jar:0.19.0]
        at com.google.cloud.tools.jib.http.FailoverHttpClient.call(FailoverHttpClient.java:265) ~[jib-core-0.19.0.jar:0.19.0]
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139) ~[jib-core-0.19.0.jar:0.19.0]
        ... 12 more
```

**Expected behavior**:
push image successful.

**Steps to reproduce**:

If Harbor version is v1.10.0 , there is no error. I can push image by java code and idea.

**Comment by k8ses** [comment]
Is jip support harbor v2.5.4 ?
