### ISSUE TITLE
Build error occurs in version 3.3.2

### ISSUE THREAD

**Issue by doljae** [GoogleContainerTools/jib#4025]
**Environment**:

- *Jib version:* 3.3.2
- *Build tool:*  Gradle 7.4.2
- *OS:* macOS
- JDK version: Zulu OpenJDK 17.0.6

**Description of the issue**:
A build error occurs when the latest version of jib(`3.3.2`) is applied to the project.

**Expected behavior**:
Project should build normally

**Steps to reproduce**:

  1. Apply latest jib(`3.3.2`) or upgrade dependency version.
  2. Try to build project or execute "Gradle Sync"
  3. Error was occured

**Build script configuration**:

```kotlin
// build.gradle.kts, just add jib plugin without any configurations
plugins {
    kotlin("jvm") apply false
    id("com.google.cloud.tools.jib") version "3.3.2"
}
```

**Log output**: 
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'myproject'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /Users/XXX/.gradle/caches/jars-9/bc33e077f18aab4d8905d3690c9e67e4/jackson-core-2.15.0.jar.

...

Caused by: org.gradle.api.GradleException: Failed to create Jar file /Users/XXX/.gradle/caches/jars-9/bc33e077f18aab4d8905d3690c9e67e4/jackson-core-2.15.0.jar.
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:55)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.instrument(InstrumentingClasspathFileTransformer.java:137)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:132)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:96)
	at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.transformFile(DefaultCachedClasspathTransformer.java:193)
	at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.lambda$cachedFile$6(DefaultCachedClasspathTransformer.java:186)
	at org.gradle.internal.UncheckedException.unchecked(UncheckedException.java:74)
	at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.lambda$transformAll$9(DefaultCachedClasspathTransformer.java:233)
	... 2 more
Caused by: java.io.IOException: Failed to process the entry 'META-INF/versions/19/com/fasterxml/jackson/core/io/doubleparser/FastDoubleSwar.class' from '/Users/XXX/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.15.0/12f334a1dc9c6d2854c43ae314024dde8b3ad572/jackson-core-2.15.0.jar'
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:161)
	at org.gradle.internal.classpath.ClasspathWalker.visitJarContents(ClasspathWalker.java:91)
	at org.gradle.internal.classpath.ClasspathWalker.visit(ClasspathWalker.java:55)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.visitEntries(InstrumentingClasspathFileTransformer.java:148)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$instrument$0(InstrumentingClasspathFileTransformer.java:139)
	at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:66)
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:53)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:151)
	... 15 more
```

**Additional Information**: 

The part using the latest version of `jackson-core` seems to be the cause of the build failure.

**Comment by emmileaf** [comment]
@doljae Thank you for bringing this to attention!

The `jib-gradle-plugin` 3.3.2 release did contain an update of jackson-bom dependency version to [2.15.0](https://github.com/GoogleContainerTools/jib/pull/3998), and looking into this issue a bit more, unfortunately this appears related to a bug in gradle (with more discussion in https://github.com/gradle/gradle/issues/24390 and https://github.com/FasterXML/jackson-core/issues/955).

As a possible workaround, would switching to gradle 7.6.1+ be an option for your project?

**Comment by doljae** [comment]
@emmileaf 
Thank you for your quick response.
I read the issue you attached. I'm not familiar with this, but I think the `jackson-core` has been affected by a bug related to backward compatibility with Gradle's JDK19 related features, so can I ask for a little clarification?

And I wonder what action jib is planning to take on this issue.
Although the cause of the issue is elsewhere, as a whole, the Gradle 7.x version is still relatively up-to-date, and many projects have jib.

**Comment by emmileaf** [comment]
> Although the cause of the issue is elsewhere, as a whole, the Gradle 7.x version is still relatively up-to-date, and many projects have jib with new features.

That is a valid point, this is definitely an inconvenience for users of the Jib gradle plugin. I think having this issue open to understand impact on users and feasibility of workarounds will be helpful for Jib's plan-of-action on this as well. 

From the perspective of Jib, a quick patch could be to revert the Jackson dependency version back to 2.14.12. That said, I’m concerned about sustainability of this in the long run, especially since this dependency is in jib-core, the incompatibility issue is specific to gradle, and is likely to continue against future versions of Jackson. It might be better to implement a gradle-plugin-specific workaround for this issue if possible. 
 
In the meanwhile, for users of the plugin (`v3.3.2`), some solutions I can think of are:
* Switching to Gradle 7.6.1+ 
* If this is not an option, possibly adding [custom dependency resolution](https://docs.gradle.org/current/userguide/resolution_rules.html) in a `buildscript` block before the `plugins` block to your project's `build.gradle` to force jackson-core version back to `2.14.2`. In Groovy syntax this looks something like:
```
buildscript {
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'com.fasterxml.jackson.core' && details.requested.name == 'jackson-core' && details.requested.version == '2.15.0') {
                details.useVersion '2.14.2'
                details.because 'incompatibility with gradle version < 7.6.1'
            }
        }
    }
}
```

Let me know if this helps!

**Comment by burkedavison** [comment]
Closing this issue as resolved.
