### ISSUE TITLE
Jib task fails due to cache metadata conflict

### ISSUE THREAD

**Issue by sergeykad** [GoogleContainerTools/jib#4031]
**Environment**:

- *Jib version: 3.3.2*
- *Build tool: Gradle 8.1*
- *OS: Ubuntu 22.04* 

**Description of the issue**:
`jib` task fails 

**Expected behavior**:
jib does not fail

**Steps to reproduce**:
Run `jib` task. The issue happens only in part of builds. We use Gradle `parallel` option and in some scenarios, another Gradle build can be running with the same user in parallel on the same machine.

**Additional inforamtion**
The issue can be related to https://github.com/GoogleContainerTools/jib/issues/922

**Log output**:
```
Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: (null exception message)
	at com.google.cloud.tools.jib.plugins.common.JibBuildRunner.runBuild(JibBuildRunner.java:285)
	at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	... 141 more
Caused by: java.nio.channels.OverlappingFileLockException
	at com.google.cloud.tools.jib.filesystem.LockFile.lock(LockFile.java:68)
	at com.google.cloud.tools.jib.cache.CacheStorageWriter.writeMetadata(CacheStorageWriter.java:361)
	at com.google.cloud.tools.jib.cache.Cache.writeMetadata(Cache.java:102)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImages(PullBaseImageStep.java:313)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:158)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:70)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
```

**Comment by ddixit14** [comment]
Hi @sergeykad, thanks for reporting this issue. Could you please provide us with more details and code to reproduce this?

**Comment by sergeykad** [comment]
The issue is occurring randomly. I think that adding  `-Djib.useOnlyProjectCache=true` fixed it, but I am not sure since I was experiencing other issues as well and was changing command line Jib parameters.

**Comment by mpeddada1** [comment]
@sergeykad thanks for the reference, this does look pretty similar to https://github.com/GoogleContainerTools/jib/issues/922. [This comment](https://github.com/GoogleContainerTools/jib/issues/3347#issuecomment-932617632) provides a nice explanation of why the `OverlappingFileLockException ` happens:

>> The OverlappingFileLockException indicates that multiple threads on the same JVM machine were able to enter into the same section of the code at the same time that is guarded by a singleton static lock.

However, the cause of the exception is still unclear. Would you be able to provide a thread dump of the deadlock? In the meantime, would it be feasible for you to run the jib tasks sequentially?

**Comment by sergeykad** [comment]
@mpeddada1 How would you suggest I obtain the thread dump? If Gradle/Jib crashes there are no threads left to dump. I did see the build just stuck a few times, but I am not sure if it is related.

What do you mean by running jib tasks sequentially? Should I set `org.gradle.parallel` or `jib.serialize` property or either will be ok?

I recently started running Jib with HTTP traffic logging and did not see any errors since. I suspect that the more verbose logging may have influenced timings that caused the errors I am trying to solve.

**Comment by mpeddada1** [comment]
IIRC there are a couple of ways in which it can be obtained. When the build hangs, we could grab the pid of jib process that's stuck (using the `ps` command) and then call `kill -3<pid>` to output the thread dump. An alternative to this would be to use tools such as [`jstack`](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jstack.html) which can also come in handy for this purpose. 

>> What do you mean by running jib tasks sequentially? Should I set org.gradle.parallel or jib.serialize property or either will be ok?

Regarding this, I was curious if forcing the jib tasks in Gradle to run sequentially makes a difference. Similar to this: https://github.com/GoogleContainerTools/jib/issues/3347#issuecomment-1137493602

**Comment by burkedavison** [comment]
Closing as stale. Please reopen if this is still an issue.
