### ISSUE TITLE
Flaky BuildImageMojoIntegrationTest failure on Mac OS continuous build

### ISSUE THREAD

**Issue by suztomo** [GoogleContainerTools/jib#4053]
http://sponge/84797d16-14c5-4e62-a8c3-2623a2e51004

```
com.google.cloud.tools.jib.maven.BuildImageMojoIntegrationTest > testBuild_tarBase FAILED
    expected to be greater than: 27617.0
    but was                    : 9079.0
        at com.google.cloud.tools.jib.maven.BuildImageMojoIntegrationTest.buildAndRunFromLocalBase(BuildImageMojoIntegrationTest.java:194)
        at com.google.cloud.tools.jib.maven.BuildImageMojoIntegrationTest.testBuild_tarBase(BuildImageMojoIntegrationTest.java:454)
```

Rebuild failed in another error http://sponge/47c4e106-e96a-4892-86e6-a8c100458d91

```
com.google.cloud.tools.jib.maven.BuildImageMojoIntegrationTest > testExecute_springBootPackaged FAILED
    java.lang.AssertionError: expected:<Hello world> but was:<null>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.google.cloud.tools.jib.api.HttpRequestTester.verifyBody(HttpRequestTester.java:35)
        at com.google.cloud.tools.jib.maven.BuildImageMojoIntegrationTest.testExecute_springBootPackaged(BuildImageMojoIntegrationTest.java:709)
```

**Comment by suztomo** [comment]
3rd attempt passed the build.
