### ISSUE TITLE
Convert Gradle config parameters `jib.container.environment` to use lazy evaluation

### ISSUE THREAD

**Issue by FrogDevelopper** [GoogleContainerTools/jib#4067]
Just like the like the [jib.container.labels](https://github.com/GoogleContainerTools/jib/issues/3094) , the `jib.container.environment` property should use lazy evaluation.
This will avoid having a mix of lazy/direct parameters set in the configuration

**Comment by diegomarquezp** [comment]
Hi @FrogDevelopper, thanks for bringing this up. [We are welcoming contributions to jib](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md) and we will gladly review any incoming PRs.

We have had similar situations with other fields (e.g. #3094 and #3709) - they may be a good start point. 

Thanks!

**Comment by FrogDevelopper** [comment]
@diegomarquezp 
I'm trying to compile locally the project (from last tag 3.3.2) but got this error

> /Users/benoit.legall/sources/rapid/jib/jib-core/src/main/java/com/google/cloud/tools/jib/configuration/ContainerConfiguration.java:41: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
> public class ContainerConfiguration {
>        ^
>      Please report this at https://github.com/google/error-prone/issues/new and include the following:
>      error-prone version: 2.10.0
>      BugPattern: NullAway
>      Stack Trace:
>      java.lang.ExceptionInInitializerError
>   	at com.uber.nullaway.NullAway.collectEntities(NullAway.java:2054)
>   	at com.uber.nullaway.NullAway.checkFieldInitialization(NullAway.java:1717)
>   	at com.uber.nullaway.NullAway.matchClass(NullAway.java:1424)
>   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
>   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:547)
>   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
>   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:818)
>   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
>   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
>   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
>   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
>   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
>   	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
>   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
>   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
>   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:601)
>   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
>   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
>   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
>   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
>   	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
>   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1423)
>   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1370)
>   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
>   	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
>   	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
>   	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
>   	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
>   	.... (a lot more follows)

Any idea why I got this and how to fix it ?

**Comment by paulvdbles** [comment]
hello there, I'd love to tackle this issue!

**Comment by Soarbh-Srivastava** [comment]
@diegomarquezp if this issue is open can you assign it to me

**Comment by dizzydroid** [comment]
@diegomarquezp I'd like to work on this issue. Could you please assign it to me?

**Comment by diegomarquezp** [comment]
@Soarbh-Srivastava @dizzydroid @paulvdbles thank you for your interest. Would you mind describing the solution and its implications (e.g. does converting to lazy evaluation change any behavior, etc)?

Re-assigning this to @ldetmer and @mpeddada1 to go over solution proposals.

**Comment by Soarbh-Srivastava** [comment]
Implementation Approach for Issue #4067

Hi @diegomarquezp ,

I'm working on implementing lazy evaluation for the jib.container.environment property as requested in #4067. Here's my current progress:

Changes Made:
- Converted field type: Changed from Map<String, String> to MapProperty<String, String> in ContainerParameters.java
- Following existing pattern: Used the labels property implementation as reference for consistency
- Maintained backward compatibility: Added setter overloads for both direct maps and providers
- Preserved system property override: Kept existing system property functionality intact

Code Changes:

ContainerParameters.java:
// Field
private MapProperty<String, String> environment;

// Constructor
environment = objectFactory.mapProperty(String.class, String.class).empty();

// Getter returns MapProperty instead of Map
public MapProperty<String, String> getEnvironment() { ... }

// Setters for both direct maps and providers
public void setEnvironment(Map<String, String> environment) { ... }
public void setEnvironment(Provider<Map<String, String>> environment) { ... }

GradleRawConfiguration.java:
return jibExtension.getContainer().getEnvironment().get();

Current Issues:
I'm encountering compilation errors in existing test files that expect the old return type:

Questions:
1. Should I update all existing test assertions to use .get() on the MapProperty?
2. What's the preferred pattern for mocking MapProperty in the Jib test suite?
3. Are there other files I should check for similar .getEnvironment() usage?

The implementation follows the established lazy evaluation pattern used by the labels property. Looking forward to your guidance on the test updates!

Thanks!

**Comment by ldetmer** [comment]
@Soarbh-Srivastava apologies but we need to confirm prioritization of this feature.  We will get back to you when we have a resource to look at your plan.

**Comment by Dimaalahdab** [comment]
if this issue is still open, i want to try to fix it so can you assign it to me

**Comment by codingkiddo** [comment]
Hi maintainers, I’d like to work on this issue.

From a first look, jib.container.labels already uses Gradle MapProperty for lazy evaluation, while jib.container.environment is still backed by a direct Map in ContainerParameters.

My proposed approach:
- Change container.environment to MapProperty<String, String>
- Initialize it from ObjectFactory in ContainerParameters
- Keep existing system-property override behavior for jib.container.environment
- Update GradleRawConfiguration to read environment.get()
- Add/update lazy-evaluation tests similar to the existing labels test

Would this approach be acceptable? If yes, could this issue be marked Accepting Contributions?
