### ISSUE TITLE
Found a flaky test in DockerManifestEntryTemplateTest.java

### ISSUE THREAD

**Issue by harshith2000** [GoogleContainerTools/jib#4136]
**Environment**:

- *Jib version:* 
- *Build tool:*  gradle-6.9.2
- *OS:* MacOS

**Description of the issue**:

Found a flaky test in DockerManifestEntryTemplateTest.testToJson

https://github.com/GoogleContainerTools/jib/blob/440bd4897c6c427cc9a491128aa76c72378d605b/jib-core/src/test/java/com/google/cloud/tools/jib/docker/json/DockerManifestEntryTemplateTest.java#L52

When comparing JSON strings, since JSON is inherently unordered (the order of keys in JSON objects is not guaranteed), it's not reliable to compare JSON strings directly if the order of the keys may vary. This makes this test flaky i.e. non-deterministic. Instead, we should parse the JSON strings into objects and compare the objects semantically. 

**Expected behavior**:
We use Jackson's ObjectMapper to convert the JSON strings into JsonNode objects. Then it compares these JsonNode objects with the equals method, which does a deep comparison of the content without considering the order of the keys.
```
ObjectMapper mapper = new ObjectMapper();
JsonNode actual = mapper.readTree(JsonTemplateMapper.toUtf8String(loadManifest));
JsonNode expected = mapper.readTree(expectedJson);
Assert.assertEquals(expected, actual);
```

I've also raised a tentative PR - https://github.com/harshith2000/jib/pull/2

**Steps to reproduce**:

I utilized the open-source tool [NonDex](https://github.com/TestingResearchIllinois/NonDex) to detect this assumption by altering the order of returned exception types.

 **To replicate:**
> Clone the Repository:
> ```
> https://github.com/GoogleContainerTools/jib.git
> ```

**Integrate NonDex:**
> Add the following snippet to the top of the build.gradle file:
> ```
> plugins {
>   id 'edu.illinois.nondex' version '2.1.1-1'
> }
> ```
> **Add to the end of the build.gradle file:**
> ```
> apply plugin: 'edu.illinois.nondex'
> subprojects {
>   apply plugin: 'edu.illinois.nondex'
> }
> ```
**Execute Test with Gradle:**
> ```
> ./gradlew --info test --tests path.to.the.TestClass.testMethod
> ```
**Run NonDex:**
> ```
> ./gradlew --info nondexTest --tests=path.to.the.TestClass.testMethod --nondexRuns=X
> ```

**Log output**: 
```
com.google.cloud.tools.jib.docker.json.DockerManifestEntryTemplateTest > testToJson FAILED
    org.junit.ComparisonFailure: expected:<[{"[Config":"config.json","RepoTags":["testregistry/testrepo:testtag"],"Layers":["layer1.tar.gz","layer2.tar.gz","layer3.tar.gz"]]}]> but was:<[{"[RepoTags":["testregistry/testrepo:testtag"],"Layers":["layer1.tar.gz","layer2.tar.gz","layer3.tar.gz"],"Config":"config.json"]}]>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.google.cloud.tools.jib.docker.json.DockerManifestEntryTemplateTest.testToJson(DockerManifestEntryTemplateTest.java:52)

```

Please let me know if I can go ahead and create a real PR for this.

**Comment by chanseokoh** [comment]
Unfortunately, the issue is that in reality we need to verify the syntactic equality in the context of container images, whose great importance I cannot stress enough. In reality, the test is not flaky, and doing semantic comparison can actually be harmful in that the test will succeed when they are not the exact same literal string. The purpose of the test is really to verify that they are literally the same string, not to see they are semantically equal.

**Comment by harshith2000** [comment]
> Unfortunately, the issue is that in reality we need to verify the syntactic equality in the context of container images, whose great importance I cannot stress enough. In reality, the test is not flaky, and doing semantic comparison can actually be harmful in that the test will succeed when they are not the exact same literal string. The purpose of the test is really to verify that they are literally the same string, not to see they are semantically equal.

I understand. But since we're comparing JSON strings, they cannot be the same strings all the time, right?

**Comment by chanseokoh** [comment]
In practice, the library always generates the same string; fortunately, there seems no randomness for the same input string. We've upgraded the library version many times, but we haven't seen any regression so far. If we spot any change to the string in a newer library version, then we need to investigate. The test is to catch this situation.

**Comment by harshith2000** [comment]
> In practice, the library always generates the same string; fortunately, there seems no randomness for the same input string. We've upgraded the library version many times, but we haven't seen any regression so far. If we spot any change to the string in a newer library version, then we need to investigate. The test is to catch this situation.

Understood. 
I also found similar flaky tests in other files, as well. 
https://github.com/harshith2000/jib/pull/1
