### ISSUE TITLE
`testWar_jetty` Has failed with AssertionError in nightly builds.

### ISSUE THREAD

**Issue by diegomarquezp** [GoogleContainerTools/jib#4182]
[Ubuntu build log](https://fusion2.corp.google.com/invocations/8d6eb7ee-39ac-4739-96f4-950fe1091a63/targets/jib%2Fgcp_ubuntu%2Fcontinuous/log)
[MacOS build log](https://fusion2.corp.google.com/invocations/6ba4a43f-3280-4e55-82d9-4d3669bf8e90/targets/jib%2Fmacos_external%2Fcontinuous/log)

Involved test:
https://github.com/GoogleContainerTools/jib/blob/0df8ed9e0e6990321f1193d214915987127962b9/jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/WarCommandTest.java#L78-L102

Failure:
```
> Task :jib-cli:integrationTest
Custom actions are attached to task ':jib-cli:integrationTest'.
Build cache key for task ':jib-cli:integrationTest' is db9261ec2a554970ebb06941f47eedb1
Task ':jib-cli:integrationTest' is not up-to-date because:
  No history is available.
Starting process 'Gradle Test Executor 7'. Working directory: /tmpfs/src/github/jib/jib-cli Command: /usr/lib/jvm/java-11-openjdk-amd64/bin/java -D_JIB_DISABLE_USER_AGENT=true -Dorg.gradle.native=false -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.6.jar_a26f6511a7813217be4cd6439d66563b/jacocoagent.jar=destfile=build/jacoco/integrationTest.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false @/tmp/gradle-worker-classpath8328713474424621879txt -Xmx512m -Dfile.encoding=US-ASCII -Duser.country=US -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 7'
Successfully started process 'Gradle Test Executor 7'
Picked up JAVA_TOOL_OPTIONS: -Xlog:os+container=error

com.google.cloud.tools.jib.cli.WarCommandTest > testWar_jetty STANDARD_OUT
    [WARN] Base image 'jetty' does not use a specific image digest - build may not be reproducible
    Getting manifest for base image jetty...
    Building dependencies layer...
    Building resources layer...
    Building classes layer...
    The base image requires auth. Trying again for jetty...
    Using base image with digest: sha256:1ddc25ec526f1ca0d47b7bf5ac04cda3dd89e081afd63646ddd198d289801454

    Container entrypoint set to [java, -jar, /usr/local/jetty/start.jar]
    Loading to Docker daemon...

com.google.cloud.tools.jib.cli.WarCommandTest > testWar_jetty FAILED
    java.lang.AssertionError: expected:<Hello world> but was:<null>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.google.cloud.tools.jib.api.HttpRequestTester.verifyBody(HttpRequestTester.java:35)
        at com.google.cloud.tools.jib.cli.WarCommandTest.testWar_jetty(WarCommandTest.java:99)
```

**Comment by meltsufin** [comment]
Duplicate for #4211.
