### ISSUE TITLE
Jib MacOS Continuous job still experiencing failure with jetty

### ISSUE THREAD

**Issue by mpeddada1** [GoogleContainerTools/jib#4237]
Ubuntu builds are green after https://github.com/GoogleContainerTools/jib/issues/4211 but the MacOS job is still running into the following failure despite the entrypoint being updated:

```
com.google.cloud.tools.jib.cli.WarCommandTest > testWar_jetty STANDARD_OUT
    [WARN] Base image 'jetty' does not use a specific image digest - build may not be reproducible
    Getting manifest for base image jetty...
    Building dependencies layer...
    Building resources layer...
    Building classes layer...
    The base image requires auth. Trying again for jetty...
    Using base image with digest: sha256:286ecf7533828cf7b2108e7d7e00884fe1334e4b925ec0797b8e4a2ee51fa1d1

    Container entrypoint set to [java, -jar, /usr/local/jetty/start.jar, --module=ee10-deploy]
    Loading to Docker daemon...

com.google.cloud.tools.jib.cli.WarCommandTest > testWar_jetty FAILED
    java.lang.AssertionError: expected:<Hello world> but was:<null>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.google.cloud.tools.jib.api.HttpRequestTester.verifyBody(HttpRequestTester.java:35)
        at com.google.cloud.tools.jib.cli.WarCommandTest.testWar_jetty(WarCommandTest.java:99)

    java.lang.RuntimeException: Command 'docker stop c7bf867ac794c844bc3010e0cc0cc3da5eaa5c0e47f3ede82b88569fcd85c641' failed: Error response from daemon: No such container: c7bf867ac794c844bc3010e0cc0cc3da5eaa5c0e47f3ede82b88569fcd85c641
        at com.google.cloud.tools.jib.Command.run(Command.java:79)
        at com.google.cloud.tools.jib.Command.run(Command.java:52)
        at com.google.cloud.tools.jib.cli.WarCommandTest.tearDown(WarCommandTest.java:44)
```

**Comment by mpeddada1** [comment]
Experimentation continued at https://github.com/GoogleContainerTools/jib/pull/4269
