### ISSUE TITLE
Authentication to Red Hat Container Registry (Openshift) doesn't work

### ISSUE THREAD

**Issue by Hi-Fi** [GoogleContainerTools/jib#576]
**Description of the issue**:
Using token obtained from Red Hat Container Registry (RHCR) in settings.xml doesn't authenticate user correctly to registry.

**Expected behavior**:
Registry is authenticating user correctly.

**Steps to reproduce**: 
mvn compile jib:build with configuration set to point to RHCR and settings.xml containing valid credentials to that. According RHCR username is "unused", amd password is token provided by UI.

**Environment**: 
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T22:39:06+03:00)
Java version: 1.8.0_131, vendor: Oracle Corporation
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

jib-maven-plugin version 0.9.6

**`jib-maven-plugin` Configuration**: 
```xml
<configuration>
	<from>
		<image>openshift-redhat-registry/testProject/test-container</image>
	</from>
	<to>
		<image>openshift-redhat-registry/testProject/${project.artifactId}:${project.version}</image>
	</to>
	<container>
		<jvmFlags>
			<jvmFlag>-Xms512m</jvmFlag>
		</jvmFlags>
	</container>
</configuration>
```

**Log output**: 
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.6:build (default-cli) on project jib-test-project: Build image failed: Tried to retrieve authentication method for openshift-redhat-registry but failed because: Failed get authentication method from 'WWW-Authenticate' header | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: Failed to authenticate with the registry because: 'service' was not found in the 'WWW-Authenticate' header, tried to parse: Bearer realm="https://openshift-redhat-registry/openshift/token" -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.6:build (default-cli) on project jib-test-project: Build image failed
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Build image failed
	at com.google.cloud.tools.jib.maven.BuildImageMojo.execute(BuildImageMojo.java:150)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.google.cloud.tools.jib.registry.RegistryErrorException: Tried to retrieve authentication method for openshift-redhat-registry but failed because: Failed get authentication method from 'WWW-Authenticate' header | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new
	at com.google.cloud.tools.jib.registry.RegistryErrorExceptionBuilder.build(RegistryErrorExceptionBuilder.java:108)
	at com.google.cloud.tools.jib.registry.AuthenticationMethodRetriever.handleHttpResponseException(AuthenticationMethodRetriever.java:104)
	at com.google.cloud.tools.jib.registry.AuthenticationMethodRetriever.handleHttpResponseException(AuthenticationMethodRetriever.java:31)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:176)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139)
	at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:338)
	at com.google.cloud.tools.jib.registry.RegistryClient.getRegistryAuthenticator(RegistryClient.java:194)
	at com.google.cloud.tools.jib.registry.RegistryAuthenticator$Initializer.initialize(RegistryAuthenticator.java:83)
	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:85)
	at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:42)
	at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:181)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.cloud.tools.jib.registry.RegistryAuthenticationFailedException: Failed to authenticate with the registry because: 'service' was not found in the 'WWW-Authenticate' header, tried to parse: Bearer realm="https://openshift-redhat-registry/openshift/token"
	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.newRegistryAuthenticationFailedException(RegistryAuthenticator.java:150)
	at com.google.cloud.tools.jib.registry.RegistryAuthenticator.fromAuthenticationMethod(RegistryAuthenticator.java:141)
	at com.google.cloud.tools.jib.registry.AuthenticationMethodRetriever.handleHttpResponseException(AuthenticationMethodRetriever.java:98)
	... 13 more
```

**Additional Information**: 
Failure also occurs when trying:
1. Login with oc CLI tool
2. Using real username and token from `oc whoami -t` as password.

With direct call with Postman to https://openshift-redhat-registry/openshift/token authenticating with user _unused_ and given token, access_token is displayed correctly in response

With real username + that `oc whoami` -t -token that /token -endpoint returns 401.

**Comment by coollog** [comment]
Ah, looks like the registry you are using does not have a `service` entry in the `Bearer` authentication challenge. We will need to handle that and use the provided registry as the service by default in our token request (which follows the [Docker Token Authentication Spec](https://docs.docker.com/registry/spec/auth/token/#requesting-a-token))

**Comment by coollog** [comment]
@Hi-Fi we just released version `0.9.7` - can you retry with the new version?

**Comment by Hi-Fi** [comment]
Authentication still seems to be have some issues.
The registry UI is at: https://openshift-redhat-registry/registry
When trying to root (https://openshift-redhat-registry) I'll get error:

> Application is not available
> The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

When trying to authenticate with JIB during "pull" (fromImage), it returns that same error (just in HTML format).
When trying to authenticate with JIB during "push" (toImage), it returns manifest error (#534)

So authentication seems to be working OK for push but not for pull.

**Comment by briandealwis** [comment]
@Hi-Fi can you confirm that you're able to use `docker pull` to pull from the registry?  Could you try the process at 
https://github.com/GoogleContainerTools/jib/issues/659#issuecomment-406369597 and report back what you see?

What is this registry?  Is it a docker-registry that you're running within your own project?  Or is it the external OpenShift registry (e.g. `registry.REGION.openshift.com`)?

**Comment by chanseokoh** [comment]
Hmm... some wild guesses:

- The repository is up and running on this `openshift-redhat-registry` host.
- When contacting the registry at wrong endpoints, the repository responses in HTML (rightfully)
   >  Application is not available
   The application is currently not serving requests at this endpoint. It may not have been started or is still starting
- After #614, it can now handle the auth challenge that does not have `service`. However, Jib may still not be contacting the right endpoint, based on what @Hi-Fi said:
   > When trying to authenticate with JIB during "pull" (fromImage), it returns that same error (just in HTML format).

**Comment by Hi-Fi** [comment]
Registry is (I think) part of Openshift on premise running version. 

Now it seemed to work (fail only at the Manifest), so yesterday there was probably some strange things going on.
