### ISSUE TITLE
Can't access gcr.io in China, Can I skip or custom hub location

### ISSUE THREAD

**Issue by helloworlde** [GoogleContainerTools/jib#604]
**Description of the issue**:
Can't access gcr.io in China, Can I skip or custom hub location
**Expected behavior**:
Can build a image 
**Steps to reproduce**: 
```
gradle jib
//or
gradle jibDockerBuild 
```

**Environment**: 
MacOS 10.13.5
Gradle 4.7

**`jib-gradle-plugin` Configuration**: 
```groovy
buildscript {
    ext {
        springBootVersion = '2.0.1.RELEASE'
        gradleDockerVersion = '0.19.2'
        sonarqubeVersion = '2.6.2'
    }
    repositories {
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("gradle.plugin.com.palantir.gradle.docker:gradle-docker:${gradleDockerVersion}")
        classpath("org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:${sonarqubeVersion}")
        classpath "gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:0.9.6"
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.palantir.docker'
apply plugin: 'org.sonarqube'
apply plugin: "com.google.cloud.tools.jib"

archivesBaseName = 'spider'


group = 'cn.com.hellowood'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
    maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
    mavenCentral()
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.springframework.boot:spring-boot-starter-aop')
    compile('org.springframework.boot:spring-boot-starter-security')
    compile('org.springframework.boot:spring-boot-starter-quartz')
    compile('org.springframework.security:spring-security-jwt:1.0.9.RELEASE')
    compile('org.springframework.security.oauth:spring-security-oauth2:2.2.1.RELEASE')
    compile('org.mybatis.spring.boot:mybatis-spring-boot-starter:1.3.1')
    compile('org.springframework.boot:spring-boot-starter-data-redis')
    compile('commons-net:commons-net:3.3')
    compile('com.alibaba:druid-spring-boot-starter:1.1.9')
    compile('io.sentry:sentry-spring:1.7.4')

    compile('com.google.protobuf:protobuf-java:2.5.0')
    compile('com.aliyun.openservices:aliyun-log-logback-appender:0.1.8')

    runtime('mysql:mysql-connector-java')
    testCompile('org.springframework.boot:spring-boot-starter-test')
}


jib.to.image = 'registry.cn-qingdao.aliyuncs.com/hellowoodes/oe'
```

**Log output**: 
```
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to gcr.io/74.125.204.82:443 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:335)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:123)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:147)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:108)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:641)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:576)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:554)
        at com.google.api.client.http.apache.ApacheHttpRequest.execute(ApacheHttpRequest.java:65)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.cloud.tools.jib.http.Connection.send(Connection.java:124)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:169)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139)
        at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:338)
        at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:213)
        at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:221)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImage(PullBaseImageStep.java:177)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:109)
        at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:54)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)

```

**Additional Information**:

**Comment by coollog** [comment]
Hi @helloworlde , you can set a different base image with `jib.from.image`. https://github.com/GoogleContainerTools/jib/issues/544#issuecomment-404297366
