### ISSUE TITLE
why to retrieve registry credentials when do task `jibDockerBuild `

### ISSUE THREAD

**Issue by ronnin** [GoogleContainerTools/jib#713]
As the task is only intented to build image to a docker daemon, not to push the image to a registry, why to retrieve registry credentials ?

**Comment by chanseokoh** [comment]
Hi @ronnin, we contact the base image registry to ensure that your image is always based on the latest up-to-date image. The log is probably about the base image.

**Comment by ronnin** [comment]
@chanseokoh, It's the `jib.to.auth` closure which blocks me. my credentials of hub.docker.com is required at `jib.to.auth`, while I build a image to the local docker daemon.

**Comment by chanseokoh** [comment]
In the following configuration, I specified a non-existing registry.

```xml
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>0.9.7</version>
        <configuration>
          <to>
            <image>non.existing.registry/repository/my-image</image>
          </to>
        </configuration>
      </plugin>
```

`mvn compile jib:build` fails as expect:
```
[INFO] Containerizing application to non.existing.registry/repository/my-image...
[INFO] 
[INFO] Retrieving registry credentials for non.existing.registry...
[INFO] Getting base image gcr.io/distroless/java...
[INFO] Building resources layer...
[INFO] Building dependencies layer...
[INFO] Building classes layer...
[INFO] Finalizing...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.095 s
[INFO] Finished at: 2018-07-25T08:51:05-04:00
[INFO] Final Memory: 30M/521M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.7:build (default-cli) on project war-example: Build image failed, perhaps you should make sure that the registry you configured exists/is spelled properly: Unknown host non.existing.registry -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

OTOH, `mvn compile jib:dockerBuild` succeeds locally.
```
[INFO] Loading to Docker daemon...
[INFO] 
[INFO] Container entrypoint set to [java, -cp, /app/libs/*:/app/resources/:/app/classes/, com.example.Main]
[INFO] 
[INFO] Built image to Docker daemon as non.existing.registry/repository/my-image
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.634 s
[INFO] Finished at: 2018-07-25T08:49:21-04:00
[INFO] Final Memory: 20M/509M
[INFO] ------------------------------------------------------------------------
```

@ronnin can you do `--stacktrace` and/or `--info` to get more info on your build?

**Comment by chanseokoh** [comment]
> It's the jib.to.auth closure which blocks me.

I see from your profile that you are in the China region. We have a report that Chinese people have a very long latency when authenticating with Docker Hub. Note that we parallelize pulling the base image and start building your image, so the log may seem like you're blocked on pushing the image.

See #648.

**Comment by coollog** [comment]
Hi @ronnin , I see you have the line `FAILURE: Build failed with an exception.` - what is the exception that you received? For timeouts, you can use the `-Djib.httpTimeout` flag (set to 0 for no timeout). I would also recommend using a different base image like `openjdk:8-jre-alpine` since `java` images are deprecated.

For the registry authentication, in version `0.9.7`, we made it so that Jib would only authenticate against a base image if it required authentication, so if you switch to that version, you should see that authentication against public Docker Hub images will not happen.

**Comment by chanseokoh** [comment]
Thanks for the update @ronnin. As for your original question about why Jib is authenticating with Docker Hub, it's because the `java:8-alpine` base image you're pulling is on Docker Hub. (See https://github.com/GoogleContainerTools/jib/issues/713#issuecomment-407738758 if you missed it.)

> Pulling base image layer sha256:38a1c0aaa6fda9a4f5f940c5c7a0622430f1faac9de367016cd5a0aed8ef4478 : 1789.553 ms
> Pulling base image layer sha256:7095154754192bfc2306f3b2b841ef82771b7ad39526537234adb1e74ae81a93 : 28158.533 ms
> Pulling base image layer sha256:5b58c996e33ea9b6701cb8935434be70cb9e5908d81a81f360b47e6f9394a1d7 : 708803.618 ms

Pulling the base image is certainly taking a lot of time from your region, as reported in #648. Note that Jib works without `docker` locally installed, which means Jib needs to fully download the base image, regardless of `docker` has previously cached `java:8-alpine` locally or not. That is, Jib manages its own local cache separately from `docker`. The good news is, if Jib successfully downloads the image once, it will be cached locally on your machine, so I think your next build using the same image will be almost instant.

**Comment by chanseokoh** [comment]
> Task :jibDockerBuild FAILED
:jibDockerBuild (Thread[Task worker for ':' Thread 7,5,main]) completed. Took 11 mins 59.198 secs.
>
> FAILURE: Build failed with an exception.

But I think there is actually a different reason that your build failed here. As @coollog said, can you provide the details of the exception?

**Comment by ronnin** [comment]
I did run `./gradlew jibDockerBuild --stacktrace`, but there was **no** extra exception with stacktrace logs. 

check it out: if running `docker pull java:8-alpine` ahead,  the `./gradlew jibDockerBuild` ran successfully.

and after that success, every time I run './gradlew jibDockerBuild', it will be a success, instantly. event if     the base image changed to `openjdk:8-jre-alpine`

as I don't know how to cleanup jib cache, I change the base image to another not used before, eg. `golang`, then run `./gradlew jibDockerBuild --stacktrace --info`, and failed:
>&gt; Task :jibDockerBuild
Task ':jibDockerBuild' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Excluding []
>
>Retrieving registry credentials for registry.hub.docker.com...
RUNNING Retrieving registry credentials for registry.hub.docker.com
No credentials could be retrieved for registry registry.hub.docker.com
Retrieving registry credentials for registry.hub.docker.com : 0.177 ms
Pulling base image manifest : 10695.118 ms
RUNNING Setting up base image caching
RUNNING Pulling base image layer sha256:55cbf04beb7001d222c71bfdeae780bda19d5cb37b8dbd65ff0d3e6a0b9b74e6
RUNNING Pulling base image layer sha256:1607093a898cc241de8712e4361dcd907898fff35b945adca42db3963f3827b3
RUNNING Pulling base image layer sha256:9a8ea045c9261c180a34df19cfc9bb3c3f28f29b279bf964ee801536e8244f2f
RUNNING Pulling base image layer sha256:d4eee24d4dacb41c21411e0477a741655303cdc48b18a948632c31f0f3a70bb8
RUNNING Pulling base image layer sha256:9c35c9787a2f7a0fbd6829b8ee0df1aebe44929788186d352b3a12f2046b3948
Setting up base image caching : 1.173 ms
RUNNING Pulling base image layer sha256:6a66653f6388693df706c282636c84c70cb8bfa2ed4068f4272c6a8817d88a1a
RUNNING Pulling base image layer sha256:102f6b19f797ad94f85324bb13126085a7e7a4c28924a603cb038d7f82fc4cc0
Pulling base image layer sha256:102f6b19f797ad94f85324bb13126085a7e7a4c28924a603cb038d7f82fc4cc0 : 3106.165 ms
Pulling base image layer sha256:9a8ea045c9261c180a34df19cfc9bb3c3f28f29b279bf964ee801536e8244f2f : 34413.185 ms
Building image to Docker daemon : 45119.094 ms
>
>&gt; Task :jibDockerBuild FAILED
:jibDockerBuild (Thread[Task worker for ':',5,main]) completed. Took 45.142 secs.
>
>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':jibDockerBuild'.
>&gt; Build to Docker daemon failed
>
>* Try:
>Run with --debug option to get more log output. Run with --scan to get full insights.
>
>* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jibDockerBuild'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Build to Docker daemon failed
        at com.google.cloud.tools.jib.gradle.BuildDockerTask.buildDocker(BuildDockerTask.java:147)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 30 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:130)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:127)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:161)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:159)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:173)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:155)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:106)
        at com.google.cloud.tools.jib.blob.BlobDescriptor.fromPipe(BlobDescriptor.java:47)
        at com.google.cloud.tools.jib.blob.InputStreamBlob.writeTo(InputStreamBlob.java:42)
        at com.google.cloud.tools.jib.registry.BlobPuller.handleResponse(BlobPuller.java:57)
        at com.google.cloud.tools.jib.registry.BlobPuller.handleResponse(BlobPuller.java:33)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:171)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:139)
        at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:338)
        at com.google.cloud.tools.jib.registry.RegistryClient.pullBlob(RegistryClient.java:266)
        at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:88)
        at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:38)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)

**Comment by ronnin** [comment]
The problem might be just related to network transportion at all.
the case of success described above might depends on the momentary low-latency at morning：
> check it out: if running docker pull java:8-alpine ahead, the ./gradlew jibDockerBuild ran successfully.

because, building with a non-used(non-cached) base image, will always failed, whether running docker pull ahead or not.

btw, running command with `-Djib.httpTimeout=0`  seems the same as running without it:
`./gradlew --info --stacktrace -Djib.httpTimeout=0 jibDockerBuild`

Thanks, all. You are very kind & helpful. @chanseokoh @coollog

**Comment by chanseokoh** [comment]
`--stacktrace` actually worked, and the exception is the socket read timeout, as suspected.
```
Caused by: java.net.SocketTimeoutException: Read timed out
at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:130)
```
`jib.httpTimeout=0` may help on the Jib-side, but I guess it won't work unless Docker Hub also sets a large timeout on the server-side, which I don't think it does.

One workaround could be, as in https://github.com/GoogleContainerTools/jib/issues/648#issuecomment-405932195, save your base image in any private or publicly available registry and configure Jib to point to it instead of Docker Hub.

> I don't know how to cleanup jib cache

FYI, the location is `$HOME/.cache/google-cloud-tools-java/jib`. You can remove the `jib` directory manually.

Lastly, I'd like to confirm one thing which could help us. It sounds like `docker pull` doesn't take much time to pull images from Docker Hub. Is that true? To test, you could pull a completely new image with `docker pull` or pull after deleting a docker-cached image with `docker rmi`. If `docker` can pull images fast while Jib can't, it's worth investigating.

**Comment by chanseokoh** [comment]
> FYI, the location is $HOME/.cache/google-cloud-tools-java/jib

This is Linux only.

**Comment by ronnin** [comment]
@chanseokoh
 `docker pull` never time out. 
according to my test for fresh pulling `openjdk:10-jre`, `docker pull`  took 2m1s,  while `jibDockerBuild` took 2m26s. `docker pull` was carried first.

so that  I need to add `-Djib.httpTimeout=0` to jib(v0.9.7) building. 
Will jib do something to avoid service-side timeout of Docker Hub?

**Comment by chanseokoh** [comment]
I see. So looks like `docker` also takes a lot of time too, not much different from Jib. (In my zone, pulling from Docker Hub is almost instant, maybe one or two seconds for large images.)

We don't have any control over Docker Hub, so I think your best bet is to use `-Djib.httpTimeout=0` (or a very long timeout like `-Djib.httpTimeout=600000) with Jib 0.9.7. That might work, I don't know. 0.9.7 has been out for a while, you can use it now. Once Jib downloads the image, it will be cached, so later builds will be faster.

Or think about putting/copying the base image into some other fast registry (https://github.com/GoogleContainerTools/jib/issues/648#issuecomment-405932195).
