### ISSUE TITLE
resource(js/css...) in springboot of docker container can not be visited

### ISSUE THREAD

**Issue by cai0329** [GoogleContainerTools/jib#854]
Description of the issue: When I use jib build springboot project which contains static resource, visit it's statuc resource occured exception as follows:

`java.io.FileNotFoundException: class path resource [static/js/index.js] cannot be resolved in the file system for resolving its last-modified timestamp
	at org.springframework.core.io.AbstractResource.lastModified(AbstractResource.java:155) ~[spring-core-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.core.io.AbstractFileResolvingResource.lastModified(AbstractFileResolvingResource.java:169) ~[spring-core-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:349) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]`

**`jib-maven-plugin` version**: 0.9.7

It resloved in https://github.com/spotify/docker-maven-plugin, can you help me reslove this problem in this useful plugin?

**Comment by coollog** [comment]
Hi @cai0329 , thanks for reporting this! Do you happen to be generating this resource after the `compile` phase?

**Comment by cai0329** [comment]
@coollog, sorry for long time no reply. Yes this resource will be generating after compile phase. And when visit the static resource from container, springboot report this.

**Comment by briandealwis** [comment]
@cai0329 I think you'll need to run a [later phase](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference) before invoking jib.  For example:
```
man generate-test-sources jib:build
```

Or you could bind jib to the same phase (or a later phase) as your script generation.

**Comment by coollog** [comment]
Closing this issue unless there's any further problems.
