### ISSUE TITLE
plugin fails to push image to insecure docker registry

### ISSUE THREAD

**Issue by naushadamin** [GoogleContainerTools/jib#872]
**Description of the issue**:
**mvn -e jib:build** fails with 'peer not authenticated error'
**Expected behavior**:
plugin pushes Docker image to repo successfully
**Steps to reproduce**: 
Run mvn -e jib:build on a maven project
**Environment**: 
OSX High Sierra
Maven 3.x
**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE

<plugin>
              <groupId>com.google.cloud.tools</groupId>
              <artifactId>jib-maven-plugin</artifactId>
              <version>0.9.7</version>
              <configuration>
              <from>
                <image>openjdk:8u171-alpine</image>
               
              </from>
              <to>
               <image>host:port/${project.artifactId}:${project.version}</image>
          
             </to>
             <container>
                <jvmFlags>
                <jvmFlag>-Xms512m</jvmFlag>
                <jvmFlag>-Xmx512m</jvmFlag>
                </jvmFlags>
             </container>
             <allowInsecureRegistries>true</allowInsecureRegistries>
              </configuration>
          </plugin> 
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by briandealwis** [comment]
Hi @naushadamin. Is this different from what you submitted as #863?  Could you please try Jib 0.9.9?

**Comment by dragontree101** [comment]
i also has problem
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.9:build (default) on project svc1: Build image failed, perhaps you should use a registry that supports HTTPS so credentials can be sent safely, or set the 'sendCredentialsOverHttp' system property to true: Required credentials for 10.10.30.38/local/spring-boot-for-test were not sent because the connection was over HTTP -> [Help 1]
```

**Comment by naushadamin** [comment]
@briandealwis Same result with 0.9.9.

Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at sun.security.ssl.SSLSessionImpl.getPeerCertificates (SSLSessionImpl.java:440)
    at org.apache.http.conn.ssl.AbstractVerifier.verify (AbstractVerifier.java:128)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket (SSLSocketFactory.java:339)

**Comment by dragontree101** [comment]
exception is 
```
Aug 23, 2018 8:30:14 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
严重: Got more than one input Future failure. Logging failures after the first
com.google.cloud.tools.jib.registry.RegistryCredentialsNotSentException: Required credentials for 10.10.30.38/local/spring-boot-for-test were not sent because the connection was over HTTP
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:212)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:244)
	at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:141)
	at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:338)
	at com.google.cloud.tools.jib.registry.RegistryClient.checkBlob(RegistryClient.java:249)
	at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:80)
	at com.google.cloud.tools.jib.builder.steps.PushBlobStep.call(PushBlobStep.java:35)
	at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:181)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by briandealwis** [comment]
That seems odd.  Could you provide some details about this registry, and is it under your control?

Does OpenSSL report any errors when running the following?
```sh
openssl s_client -connect 10.10.30.38:443 < /dev/null
```

Would you please follow the procedure in the FAQ for [_How to I view the debug log for Jib?_](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-view-debug-logs-for-jib) and attach the full log here? (Eliding your internal identifiers, of course.)

In the meantime, providing you are running on a trusted network, you can run with `mvn -DsendCredentialsOverHttp=true`.  It's not a recommended option as your user credentials are sent in the clear.

**Comment by coollog** [comment]
@naushadamin @dragontree101 Did the procedures @briandealwis work for you?

**Comment by naushadamin** [comment]
@coollog - I am not sure that the recommendations made by @briandealwis was to resolve the issue reported by me. Symptoms reported by @dragontree101 and me are different

**Comment by briandealwis** [comment]
@naushadamin you've provided more information on #863 so let's move diagnosis there.

@dragontree101 please open a new issue if you've been unable to resolve your problem. Please also let us know if you are using a proxy!
