### ISSUE TITLE
Build image failed on child module

### ISSUE THREAD

**Issue by matt-shaw** [GoogleContainerTools/jib#907]
Description of the issue:

When I build our multi-module project using maven I get an error when creating the build image for one of the child modules, all of the others seem fine.  If I build that child project on it's own everything works.  I don't understand the error.

Expected behaviour:

It should all build fine.

Steps to reproduce:

Ran ```mvn clean deploy -DskipTests``` at the parent root project

Environment:
Maven 3.5.0
JIB Maven Plugin 0.9.10-SNAPSHOT from a few days ago (I need the label feature)

`jib-maven-plugin` Configuration: 
```
	  <build>
		<plugins>
		  <plugin>
			<groupId>com.google.cloud.tools</groupId>
			<artifactId>jib-maven-plugin</artifactId>
			<version>0.9.10-SNAPSHOT</version>
			<configuration>
			  <to>
				<image>${docker.push.to.repo}/${docker.image.name}</image>
				<auth>
				  <username>XXX</username>
				  <password>XXX</password>
				</auth>
			  </to>
			  <from>
				<image>${docker.pull.from.repo}/${docker.base.image}</image>
				<auth>
				  <username>XXX</username>
				  <password>XXX</password>
				</auth>
			  </from>
			  <container>	
				<jvmFlags>
				  <jvmFlag>-XX:+UnlockExperimentalVMOptions</jvmFlag>
				  <jvmFlag>-XX:+UseCGroupMemoryLimitForHeap</jvmFlag>
				</jvmFlags>
				<labels>
					<owner>aow</owner>
					<system>${project.groupId}</system>
					<version>${project.version}</version>
				</labels>
				<ports>
				  <port>${docker.expose.port}</port>
				</ports>
				<useCurrentTimestamp>true</useCurrentTimestamp>				
			  </container>
			  <allowInsecureRegistries>true</allowInsecureRegistries>
			</configuration>
			<executions>
			  <execution>
			    <phase>deploy</phase>
				  <goals>
				    <goal>build</goal>
					<goal>exportDockerContext</goal>
				  </goals>
			  </execution>
			</executions>
		  </plugin>
		</plugins>
	  </build>
```

Log output:
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10-SNAPSHOT:build (default) on project aor-equipment-app: Build image failed: entry 'app/libs//pom.xml' closed at '2638' before the '5069' bytes specified in the header were written -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10-SNAPSHOT:build (default) on project aor-equipment-app: Build image failed
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Build image failed
	at com.google.cloud.tools.jib.maven.BuildImageMojo.execute(BuildImageMojo.java:140)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.io.IOException: entry 'app/libs//pom.xml' closed at '2638' before the '5069' bytes specified in the header were written
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.closeArchiveEntry(TarArchiveOutputStream.java:419)
	at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeEntriesAsTarArchive(TarStreamBuilder.java:52)
	at com.google.cloud.tools.jib.blob.WriterBlob.writeTo(WriterBlob.java:36)
	at com.google.cloud.tools.jib.cache.CacheWriter.writeLayer(CacheWriter.java:73)
	at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:121)
	at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:37)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.io.IOException: This archive contains unclosed entries.
		at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:289)
		at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:306)
		at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeEntriesAsTarArchive(TarStreamBuilder.java:54)
		... 10 more
[ERROR] 
```

**Comment by briandealwis** [comment]
Hi @matt-shaw — that should have been fixed in #891.  Could you please try re-pulling and rebuilding?

**Comment by coollog** [comment]
To repull and rebuild, run:

**Comment by coollog** [comment]
To repull and rebuild, run:

1. Navigate to the directory `jib-maven-plugin`
1. Pull latest changes `git pull`
1. Install the SNAPSHOT version: `./mvnw -U -DskipTests clean install`
1. Use the `0.9.10-SNAPSHOT` version in your project.

**Comment by matt-shaw** [comment]
I just pulled down the latest zip file and re-built (I'm behind a firewall) and I got the same error?

**Comment by matt-shaw** [comment]
It now fails in the same place but with a different error;

```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10-SNAPSHOT:exportDockerContext (default) on project aor-equipment-app: Export Docker context failed, perhaps you should check if `targetDir` is set correctly: C:\Repos\aoref\aor-equipment\aor-equipment-app\target\jib-docker-context\snapshot-libs\pom.xml -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10-SNAPSHOT:exportDockerContext (default) on project aor-equipment-app: Export Docker context failed, perhaps you should check if `targetDir` is set correctly
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Export Docker context failed, perhaps you should check if `targetDir` is set correctly
	at com.google.cloud.tools.jib.maven.DockerContextMojo.execute(DockerContextMojo.java:101)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.nio.file.FileAlreadyExistsException: C:\Repos\aoref\aor-equipment\aor-equipment-app\target\jib-docker-context\snapshot-libs\pom.xml
	at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:124)
	at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:278)
	at java.nio.file.Files.copy(Files.java:1274)
	at com.google.cloud.tools.jib.filesystem.FileOperations.lambda$copy$0(FileOperations.java:43)
	at com.google.cloud.tools.jib.filesystem.FileOperations.copy(FileOperations.java:50)
	at com.google.cloud.tools.jib.frontend.JavaDockerContextGenerator.generate(JavaDockerContextGenerator.java:221)
	at com.google.cloud.tools.jib.maven.DockerContextMojo.execute(DockerContextMojo.java:86)
	... 22 more
[ERROR] 
```

**Comment by briandealwis** [comment]
Looking back I missed a key detail here:
```
Caused by: java.io.IOException: entry 'app/libs//pom.xml' closed at '2638' before the '5069' bytes specified in the header were written
```
Why is there a `pom.xml` being copied into the libs area?  There should only be jars.

Are your projects attaching their pom.xml as a secondary artifact?

**Comment by briandealwis** [comment]
@matt-shaw I lost track of this issue (sorry).  Jib just copies a project's dependencies — which are normally `jar` files — into place.  `pom.xml`s are not typically included as a build artifact.  Are you using the `build-helper-maven-plugin` to attach additional artifacts?

Could you please either include your `pom.xml`s or  create a small example project that demonstrates the issue?

**Comment by briandealwis** [comment]
Oops didn't mean to close.

**Comment by coollog** [comment]
@matt-shaw Just checking back in for any updates. Are you still experiencing this problem / if so, could you provide us more details as @briandealwis mentioned in https://github.com/GoogleContainerTools/jib/issues/907#issuecomment-423548691?

**Comment by coollog** [comment]
Closing due to inactivity - feel free to reopen if still relevant.
