### ISSUE TITLE
Multiple jib tasks cannot run in parallel due to cache directory conflict

### ISSUE THREAD

**Issue by anuraaga** [GoogleContainerTools/jib#922]
**Description of the issue**:
When there are multiple jib projects in a build run simultaneously (using `--parallel` or setting the gradle property `org.gradle.parallel `), the tasks will fail due to conflicting accesses to the shared cache directory.

**Expected behavior**:
Multiple jib tasks should be invokable in a parallel build, at least serializing the tasks themselves with locks if not proper parallel execution.

**Steps to reproduce**: 

1) git clone https://github.com/anuraaga/gradle-jib-multiproject-example
2) cd gradle-jib-multiproject-example
3) ./gradlew jibBuildTar --stacktrace

May need to do `rm -rf ~/.cache/google-cloud-tools-java/jib` to clear cache first to repro.

As this is a race condition, it's not guaranteed this will repro, but I think it's likely enough on a reasonably fast computer.

**Environment**: 

Linux

**`jib-gradle-plugin` Configuration**: 
Two targets in the same build with 
```groovy
plugins {
  id 'com.google.cloud.tools.jib' version '0.9.10'
}

apply plugin: 'java'

dependencies {
  compile project(':lib')
}

jib {
  from {
    image = 'openjdk:10-jre-slim'
  }
  to {
    image = 'gcr.io/test-project/test-image'
  }
  container {
    mainClass = 'Main'
  }
}
```

**Log output**: 

```
Caused by: java.nio.channels.OverlappingFileLockException
        at com.google.cloud.tools.jib.json.JsonTemplateMapper.readJsonFromFileWithLock(JsonTemplateMapper.java:83)
        at com.google.cloud.tools.jib.cache.Cache.loadCacheMetadata(Cache.java:62)
        at com.google.cloud.tools.jib.cache.Cache.init(Cache.java:47)
        at com.google.cloud.tools.jib.cache.Caches.<init>(Caches.java:122)
        at com.google.cloud.tools.jib.cache.Caches.<init>(Caches.java:31)
        at com.google.cloud.tools.jib.cache.Caches$Initializer.init(Caches.java:106)
        at com.google.cloud.tools.jib.builder.BuildSteps.run(BuildSteps.java:202)
        at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:173)
        at com.google.cloud.tools.jib.gradle.BuildTarTask.buildTar(BuildTarTask.java:142)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
```

or in a different build, this similar error

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.cache.CacheDirectoryCreationException: Could not create cache directory: /root/.cache/google-cloud-tools-java/jib
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Caches$Initializer.ensureOwnership(Caches.java:63)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Caches$Initializer.init(Caches.java:100)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.BuildSteps.run(BuildSteps.java:202)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:173)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:133)
Step #3 - "curio-generated-build-all": ... 50 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.FileAlreadyExistsException: /root/.cache/google-cloud-tools-java/jib/.jib
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Caches$Initializer.ensureOwnership(Caches.java:60)
Step #3 - "curio-generated-build-all": ... 54 more
```
or this one in a different build
```
java.util.zip.ZipException: Not in GZIP format
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
        at com.google.cloud.tools.jib.cache.CacheWriter.getDiffId(CacheWriter.java:146)
        at com.google.cloud.tools.jib.cache.CacheWriter.getCachedLayer(CacheWriter.java:126)
        at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:91)
        at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:38
```

**Additional Information**: 

I guess cache access should acquire a file lock first - a Java synchronized might work too but not sure if the tasks are guaranteed to run in the same gradle daemon.

**Comment by anuraaga** [comment]
I'm currently using this workaround to lock around the entire task, but ideally similar locking only happened when accessing the shared cache instead.

```groovy
    // Workaround https://github.com/GoogleContainerTools/jib/issues/922
    project.tasks.withType(com.google.cloud.tools.jib.gradle.BuildImageTask) {
        def lockChannel = new RandomAccessFile(rootProject.file('build/jib.lock'), 'rw').getChannel()
        def lock = null
        doFirst {
            println 'Acquiring lock'
            while (true) {
                try {
                    lock = lockChannel.lock()
                    break
                } catch (OverlappingFileLockException e) {
                    sleep 100
                }
            }
            println 'Acquired lock'
        }
        doLast {
            println 'Releasing lock'
            lock.release()
        }
    }
```

**Comment by coollog** [comment]
Hi @anuraaga , thanks for filing this! This provides us with a solid example of concurrent cache write conflicts that we are addressing with the new cache design (the proposal is under review currently at #878). I will keep this issue open to make sure we address all the errors you outlined.

**Comment by velo** [comment]
FWIW, using maven threads also cause this issue `mvn clean install -T2`

Settings `useOnlyProjectCache` to `true` bypass the problem by not caching

```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build (default) on project service-cassandra-versions: Execution default of goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build failed.: OverlappingFileLockException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build (default) on project service-cassandra-versions: Execution default of goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.nio.channels.OverlappingFileLockException
    at sun.nio.ch.SharedFileLockTable.checkList (FileLockTable.java:255)
    at sun.nio.ch.SharedFileLockTable.add (FileLockTable.java:152)
    at sun.nio.ch.FileChannelImpl.lock (FileChannelImpl.java:1063)
    at com.google.cloud.tools.jib.json.JsonTemplateMapper.readJsonFromFileWithLock (JsonTemplateMapper.java:83)
    at com.google.cloud.tools.jib.cache.Cache.loadCacheMetadata (Cache.java:62)
    at com.google.cloud.tools.jib.cache.Cache.init (Cache.java:47)
    at com.google.cloud.tools.jib.cache.Caches.<init> (Caches.java:122)
    at com.google.cloud.tools.jib.cache.Caches.<init> (Caches.java:31)
    at com.google.cloud.tools.jib.cache.Caches$Initializer.init (Caches.java:106)
    at com.google.cloud.tools.jib.builder.BuildSteps.run (BuildSteps.java:202)
    at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build (BuildStepsRunner.java:173)
    at com.google.cloud.tools.jib.maven.BuildImageMojo.execute (BuildImageMojo.java:136)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build (default) on project service-jwt-payload: Execution default of goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build failed.: OverlappingFileLockException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build (default) on project service-jwt-payload: Execution default of goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.nio.channels.OverlappingFileLockException
    at sun.nio.ch.SharedFileLockTable.checkList (FileLockTable.java:255)
    at sun.nio.ch.SharedFileLockTable.add (FileLockTable.java:152)
    at sun.nio.ch.FileChannelImpl.lock (FileChannelImpl.java:1063)
    at com.google.cloud.tools.jib.json.JsonTemplateMapper.readJsonFromFileWithLock (JsonTemplateMapper.java:83)
    at com.google.cloud.tools.jib.cache.Cache.loadCacheMetadata (Cache.java:62)
    at com.google.cloud.tools.jib.cache.Cache.init (Cache.java:47)
    at com.google.cloud.tools.jib.cache.Caches.<init> (Caches.java:122)
    at com.google.cloud.tools.jib.cache.Caches.<init> (Caches.java:31)
    at com.google.cloud.tools.jib.cache.Caches$Initializer.init (Caches.java:106)
    at com.google.cloud.tools.jib.builder.BuildSteps.run (BuildSteps.java:202)
    at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build (BuildStepsRunner.java:173)
    at com.google.cloud.tools.jib.maven.BuildImageMojo.execute (BuildImageMojo.java:136)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:200)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:196)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by coollog** [comment]
This has been fixed via the new cache mechanism and will be available in the next release (version `0.10.0`).

**Comment by coollog** [comment]
Hi @anuraaga  , @velo , we have released version `0.10.0` which allows for multiple Jib builds to be executed simultaneously.

**Comment by anuraaga** [comment]
Finally got to try this out and ran into #1273 for any watchers of this issue

**Comment by chanseokoh** [comment]
@bademux is it #3347? Hard to know what exactly you are hitting.

**Comment by sergeykad** [comment]
Getting a similar issue with Jib v3.3.2, Gradle 8.1.0 and `org.gradle.parallel=true`. It happens sporadically and I have no reliable way to reproduce it.

The temporary fix proposed by @bademux does not help.

```
Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: (null exception message)
	at com.google.cloud.tools.jib.plugins.common.JibBuildRunner.runBuild(JibBuildRunner.java:285)
	at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	... 113 more
Caused by: java.nio.channels.OverlappingFileLockException
	at com.google.cloud.tools.jib.filesystem.LockFile.lock(LockFile.java:68)
	at com.google.cloud.tools.jib.cache.CacheStorageWriter.writeMetadata(CacheStorageWriter.java:361)
	at com.google.cloud.tools.jib.cache.Cache.writeMetadata(Cache.java:102)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImages(PullBaseImageStep.java:313)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:158)
	at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:70)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
```
