### ISSUE TITLE
Gradle: proxy-configuration not followed

### ISSUE THREAD

**Issue by lostiniceland** [GoogleContainerTools/jib#943]
**Description of the issue**:
The jib-gradle-plugin uses the google-api-client without passing the proxy-configuration from Gradle. The connection to https://registry.hub.docker.com fails with an 407.

**Expected behavior**:
Proxy-configuration, including authentication with username password, is used when necessary (configured in gradle.properties).

**Steps to reproduce**: 
- Have a proxy with authentication configured for outgoing connections
- Configure Gradle to use proxy (see additional information)
- Run jib task

**Environment**: 
gradle-jib-plugin 0.9.10
Windows 10, Gradle 4.9 

**`jib-gradle-plugin` Configuration**: 
```groovy
jib {
  from {
    image = 'library/openjdk:8-jre-alpine'
  }
  to {
    image = 'my/image:label'
  }
  container {
    mainClass = 'x.Y'
    ports = ['9090']
    jvmFlags = ['-Xms128m', '-Xdebug']
  }
}
```

**Log output**: 
```
Execution failed for task ':jib'.
> Build image failed

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jib'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:273)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:258)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Build image failed
        at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:136)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:786)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:753)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: com.google.api.client.http.HttpResponseException: 407 Proxy Authentication Required
...HTML from Proxy telling I am not authenticated...

        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
        at com.google.cloud.tools.jib.http.Connection.send(Connection.java:161)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:227)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.callWithAllowInsecureRegistryHandling(RegistryEndpointCaller.java:150)
        at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:140)
        at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:356)
        at com.google.cloud.tools.jib.registry.RegistryClient.getRegistryAuthenticator(RegistryClient.java:207)
        at com.google.cloud.tools.jib.registry.RegistryAuthenticator$Initializer.initialize(RegistryAuthenticator.java:87)
        at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:94)
        at com.google.cloud.tools.jib.builder.steps.AuthenticatePushStep.call(AuthenticatePushStep.java:44)
        at com.google.common.util.concurrent.CombinedFuture$CallableInterruptibleTask.runInterruptibly(CombinedFuture.java:181)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)

```

**Additional Information**: 
Gradle is configured to use the following proxy-configuration via gradle.properties
```
systemProp.http.proxyHost=our.stupid.proxy.com
systemProp.http.proxyPort=3128
systemProp.http.proxyUser=user
systemProp.http.proxyPassword=password
systemProp.http.nonProxyHosts=*.internal.com|localhost|127.0.0.1
systemProp.https.proxyHost=our.stupid.proxy.com
systemProp.https.proxyPort=3128
systemProp.https.proxyUser=user
systemProp.https.proxyPassword=password
systemProp.https.nonProxyHosts=*.internal.com|localhost|127.0.0.1
```

**Comment by chanseokoh** [comment]
Since you got "407 Proxy Authentication Required", I think Jib is already connecting to your proxy server, not directly to `https://registry.hub.docker.com/`. It is just that when Jib is interacting with the proxy server, it did not give a username and a password (via the `Proxy-Authenticate` header, I believe).

Something's still itching me, but I see you have duplicate lines in your `gradle.properties`:
```
...
systemProp.https.proxyUser=user
systemProp.https.proxyPassword=password
...
systemProp.https.proxyUser=user
systemProp.https.proxyPassword=password
...
```
Also, is it true that you are pushing to `https://registry.hub.docker.com/`? Can you also try `gradle jibDockerBuild --info` to check if pulling the base image `library/openjdk:8-jre-alpine` is OK at least?

**Comment by lostiniceland** [comment]
The duplicate https setting was a c&p mistake in this issue. I've corrected it.

At the moment I am working around the issue by using jibDockerBuild which also only works if I point it to a intern docker-registry-mirror using `image = 'docker.mycompany.com:5000/library/openjdk:8-jre-alpine'`

At the moment I only need a local image without pushing. That works using the jibDockerBuild.
From your question I fear that the jib goal is always trying to push to dockerhub? That would explain the proxy...

Anyway, I think the issue is still relevant, since it is not passing username, password to the client.

**Comment by chanseokoh** [comment]
First of all, Jib itself does not take any part in or mind the proxy business at all; there is no proxy-related code in Jib. It is just the standard JDK that will take care of proxy connection here in the standard way of setting some relevant system properties that JDK understands.

Apparently, `systemProp.https.proxyHost=our.stupid.proxy.com` is working, since you are already connecting to your proxy and getting 407. So, I think perhaps you may be providing incorrect username and password for your proxy? For example, one thing I know is that, if your proxy requires NTLM Auth, you may need to provide the auth domain, which can be given in the form of `domain/user` to `https.proxyUser` or set `http.auth.ntlm.domain`.

I suggest you to consult an network admin or export in your company for help.

> From your question I fear that the jib goal is always trying to push to dockerhub?

To answer, the `jib` task pushes to the target registry directly. It does not talk to a local Docker daemon, and in fact, the `jib` task works even if there is no Docker on your local machine. It does not make use of Docker at all.

**Comment by TadCordle** [comment]
Closing due to inactivity, feel free to reopen if this is still a problem.
