### ISSUE TITLE
Flaky integration test with LocalRegistry(5000, "testuser", "testpassword")

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#965]
I've seen this error a few times. Looking at the code of `LocalRegistry`. One possibility I'm thinking is that the local registry in the image needs some time to be fully operational, while the test code is trying to access the registry too early.

```
com.google.cloud.tools.jib.gradle.JibPluginIntegrationTest > testDockerDaemon_defaultTarget FAILED
    java.lang.RuntimeException: Command 'docker login localhost:5000 -u testuser --password-stdin' failed: Error response from daemon: Get http://localhost:5000/v2/: EOF
        at com.google.cloud.tools.jib.Command.run(Command.java:68)
        at com.google.cloud.tools.jib.registry.LocalRegistry.login(LocalRegistry.java:145)
        at com.google.cloud.tools.jib.registry.LocalRegistry.pullAndPushToLocal(LocalRegistry.java:135)
        at com.google.cloud.tools.jib.gradle.JibPluginIntegrationTest.setup(JibPluginIntegrationTest.java:177)
```

**Comment by chanseokoh** [comment]
Failing at the same location but with a slightly different error.

```
com.google.cloud.tools.jib.gradle.JibPluginIntegrationTest > testDockerDaemon_defaultTarget FAILED
    java.lang.RuntimeException: Command 'docker login localhost:5000 -u testuser --password-stdin' failed: Error response from daemon: Get http://localhost:5000/v2/: read tcp [::1]:35828->[::1]:5000: read: connection reset by peer
        at com.google.cloud.tools.jib.Command.run(Command.java:68)
        at com.google.cloud.tools.jib.registry.LocalRegistry.login(LocalRegistry.java:145)
        at com.google.cloud.tools.jib.registry.LocalRegistry.pullAndPushToLocal(LocalRegistry.java:135)
        at com.google.cloud.tools.jib.gradle.JibPluginIntegrationTest.setup(JibPluginIntegrationTest.java:177)
```

**Comment by coollog** [comment]
Someone I feel like this might be due to us restarting the Docker daemon - it will kill the local registries running and cause the read to be EOF or the connection to be terminated.

**Comment by chanseokoh** [comment]
I still believe the reason for the frequent failure on MacOS is that the Docker registry may not be ready. This is easy to reproduce. For example, if I can create an image from `registry:2` that sleeps for a while before running the registry, `docker push` fails with the "connection reset by peer" error.

- `my-entrypoint.sh`:
```sh
#!/bin/sh

sleep 5s

exec /entrypoint.sh "$@"
```
- `Dockerfile`:
```Dockerfile
FROM registry:2

COPY my-entrypoint.sh /

ENTRYPOINT ["/my-entrypoint.sh"]
CMD ["/etc/docker/registry/config.yml"]
```
```
$ docker build -t my-registry:2 .
$ docker run -d -p 5000:5000 --restart=always --name my-registry my-registry:2
7dc0c49ffca09e9ac0e737e024ec6fba054a1bde1aea068311326330fce23e39

# Connection reset by peer, because the registry is not yet running
$ docker push localhost:5000/ubuntu:18.04
The push refers to repository [localhost:5000/ubuntu]
Get http://localhost:5000/v2/: read tcp [::1]:57062->[::1]:5000: read: connection reset by peer

# Still not yet running
$ docker push localhost:5000/ubuntu:18.04
The push refers to repository [localhost:5000/ubuntu]
Get http://localhost:5000/v2/: read tcp [::1]:57096->[::1]:5000: read: connection reset by peer

# Registry up and running
$ docker push localhost:5000/ubuntu:18.04
The push refers to repository [localhost:5000/ubuntu]
8d7ea83e3c62: Pushed 
6a061ee02432: Pushed 
f73b2816c52a: Pushed 
6267b420796f: Pushed 
a30b835850bf: Pushed 
18.04: digest: sha256:a819482773d99bbbb570626b6101fa37cd93a678581ee564e89feae903c95f20 size: 1357
```
